export type FireDetailPage = {
  slug: string;
  title: string;
  eyebrow: string;
  intro: string[];
  leadImage: string;
  leadAlt: string;
  sectionTitle: string;
  sectionBody: string[];
  bulletsTitle: string;
  bullets: string[];
  featuresTitle?: string;
  features?: string[];
  suitableFor: string[];
  ctaTitle: string;
  ctaText: string;
  ctaButton: string;
};

export const fireSystemsPage = {
  title: "Fire Systems",
  eyebrow: "Complete fire safety solutions",
  intro: [
    "Fire safety is one of the most important responsibilities for any property owner, landlord, business or facilities manager. At DM Fire & Security, we provide complete fire system solutions designed to protect people, property and day to day operations.",
    "From fire alarm installation and emergency lighting to extinguishers, smoke ventilation, nurse call systems and compliance certification, our team delivers professional fire safety services from initial survey through installation, testing, maintenance and documentation.",
    "We work with residential properties, commercial buildings, offices, retail premises, care environments, apartment blocks, schools, warehouses and managed sites.",
  ],
  image: "/fire-systems-card.png",
  sectionTitle: "Complete fire safety solutions for your property",
  sectionBody: [
    "Every building has different risks, layouts and compliance requirements. That is why we do not use a one size fits all approach. We assess your premises carefully, recommend the most suitable system and ensure every installation is completed to a high professional standard.",
  ],
  benefits: [
    "Improve life safety",
    "Support legal and insurance compliance",
    "Detect fire risks early",
    "Maintain safe evacuation routes",
    "Protect assets and property",
    "Keep systems tested, serviced and documented",
    "Reduce downtime through reliable maintenance",
  ],
  servicesIntro:
    "Our fire system services cover design, installation, testing, maintenance and certification, giving you one accountable team across every stage of the fire safety journey.",
  services: [
    {
      title: "Fire Alarm Systems",
      text: "We design, install and maintain fire alarm systems for residential, commercial and managed properties, with conventional and addressable options tailored to the building.",
      href: "/fire-systems/fire-alarm-systems",
      iconSrc: "/service-icons/fire-alarms.svg",
    },
    {
      title: "Fire Extinguishers",
      text: "Supply, placement, commissioning, annual servicing, refills and replacements for the right extinguisher in the right location.",
      href: "/fire-systems/fire-extinguishers",
      iconSrc: "/service-icons/fire-extinguishers.svg",
    },
    {
      title: "Emergency Lighting",
      text: "Escape route lighting, open area lighting and high risk task lighting designed, installed and maintained for safer evacuation.",
      href: "/fire-systems/emergency-lighting",
      iconSrc: "/service-icons/emergency-lighting.svg",
    },
    {
      title: "Automatic Opening Ventilation",
      text: "Smoke ventilation systems including window vents, roof hatches, louvres and smoke shaft integration with fire alarms.",
      href: "/fire-systems/automatic-opening-ventilation",
      iconSrc: "/service-icons/sprinklers.svg",
    },
    {
      title: "Nurse Call & Emergency Communication",
      text: "Emergency communication systems for care, assisted living and managed environments where rapid support matters most.",
      href: "/fire-systems/nurse-call-emergency-communication",
      iconSrc: "/service-icons/intruder-alarms.svg",
    },
    {
      title: "PA & Speaker Systems",
      text: "Clear voice announcement and speaker systems for commercial, public access and managed environments.",
      href: "/fire-systems/pa-speaker-systems",
      iconSrc: "/service-icons/kitchen-suppression.svg",
    },
    {
      title: "Certification & Compliance",
      text: "Testing, certification and documentation that help landlords, businesses and facilities teams stay organised and compliant.",
      href: "/fire-systems/certification-compliance",
      iconSrc: "/service-icons/dry-wet-risers.svg",
    },
  ],
  whyTitle: "Why choose DM Fire & Security?",
  whyBody:
    "DM Fire & Security provides a complete service from consultation to completion. Our team focuses on safe installation, clear communication, reliable workmanship and long term support.",
  whyPoints: [
    "Professional site surveys",
    "Clear recommendations",
    "Quality system installation",
    "Compliance focused workmanship",
    "Planned servicing and maintenance",
    "Fast repairs and support",
    "Clear certification and documentation",
    "One accountable team for fire and security",
  ],
  suitableFor: [
    "Residential properties",
    "Commercial buildings",
    "Offices and retail units",
    "Apartment blocks",
    "Care homes and assisted living facilities",
    "Schools and education buildings",
    "Warehouses and industrial sites",
    "Landlord managed properties",
    "Facilities management portfolios",
  ],
  ctaTitle: "Need a reliable fire system for your property?",
  ctaText:
    "Contact DM Fire & Security today to arrange a survey, request a quote or discuss your fire safety requirements.",
  ctaButton: "Arrange a Fire Survey",
} as const;

export const fireDetailPages: FireDetailPage[] = [
  {
    slug: "fire-alarm-systems",
    title: "Fire Alarm Systems",
    eyebrow: "Early warning & dependable detection",
    intro: [
      "A reliable fire alarm system is essential for protecting people, property and business operations. At DM Fire & Security, we design, install and maintain fire alarm systems that provide early warning, dependable performance and compliance support for a wide range of buildings.",
      "Whether you require a new installation, system upgrade, repair, commissioning or scheduled maintenance, our team can provide a complete fire alarm service tailored to your property.",
    ],
    leadImage: "/fire-systems-card.png",
    leadAlt: "Fire alarm panel and life safety equipment",
    sectionTitle: "Professional fire alarm installation",
    sectionBody: [
      "Every fire alarm system should be designed around the layout, usage and risk level of the building. Our team assesses your premises and recommends the most suitable system to ensure the correct level of fire detection and warning coverage.",
      "We install systems for homes, commercial buildings, offices, shops, apartment blocks, care facilities, schools, warehouses and managed properties.",
    ],
    bulletsTitle: "Our fire alarm services include",
    bullets: [
      "Fire alarm system design and planning",
      "Conventional fire alarm systems",
      "Addressable fire alarm systems",
      "Fire alarm panel installation",
      "Smoke detector and heat detector installation",
      "Manual call point installation",
      "Sounder and beacon installation",
      "System commissioning and certification",
      "Fire alarm upgrades and modifications",
      "Fault finding and repairs",
      "Scheduled servicing and maintenance",
      "Emergency callouts and support",
    ],
    featuresTitle: "Designed for safety and compliance",
    features: [
      "Conventional systems suit smaller or simpler buildings divided into detection zones.",
      "Addressable systems suit larger or more complex sites where individual devices need to be identified quickly.",
      "Regular maintenance keeps your system reliable, documented and ready to operate when needed.",
    ],
    suitableFor: [
      "Homes and private residences",
      "Offices and commercial premises",
      "Shops and retail units",
      "Apartment blocks",
      "Care homes",
      "Schools and education buildings",
      "Warehouses and industrial properties",
      "Landlords and property managers",
    ],
    ctaTitle: "Protect your property with a professionally installed fire alarm system.",
    ctaText: "Contact DM Fire & Security today to arrange a fire alarm survey or request a quote.",
    ctaButton: "Request a Fire Alarm Survey",
  },
  {
    slug: "fire-extinguishers",
    title: "Fire Extinguishers",
    eyebrow: "Correct extinguishers for the right risk",
    intro: [
      "Fire extinguishers are a vital part of any fire safety strategy. They provide immediate protection in the early stages of a fire and help support the safety of occupants, staff and visitors.",
      "DM Fire & Security supplies, installs and maintains fire extinguishers for residential, commercial and managed properties, ensuring the correct extinguisher types are provided for the risks within your building.",
    ],
    leadImage: "/fire-systems-card.png",
    leadAlt: "Fire extinguisher and life safety equipment",
    sectionTitle: "Correct extinguishers for the right risk",
    sectionBody: [
      "Different fire risks require different extinguisher types. Our team can assess your premises and recommend the correct extinguishers based on the type of environment, equipment, materials and usage of the building.",
      "We help ensure your extinguishers are suitable, correctly positioned and properly maintained.",
    ],
    bulletsTitle: "Our fire extinguisher services include",
    bullets: [
      "Fire extinguisher supply",
      "Fire extinguisher installation",
      "Extinguisher commissioning",
      "Annual servicing and maintenance",
      "Refills and replacements",
      "Extinguisher location planning",
      "Fire extinguisher signage",
      "Staff guidance and basic user advice",
      "Fire extinguisher servicing records",
      "Compliance documentation",
    ],
    featuresTitle: "Extinguisher types available",
    features: [
      "Water extinguishers",
      "Foam extinguishers",
      "CO₂ extinguishers",
      "Powder extinguishers",
      "Wet chemical extinguishers",
    ],
    suitableFor: [
      "Homes and rental properties",
      "Offices and workplaces",
      "Shops and retail premises",
      "Restaurants and kitchens",
      "Warehouses and industrial units",
      "Schools and education buildings",
      "Care homes and healthcare environments",
      "Landlords and facilities managers",
    ],
    ctaTitle: "Need extinguishers supplied, installed or serviced?",
    ctaText: "Contact DM Fire & Security today to arrange professional fire extinguisher support.",
    ctaButton: "Book Extinguisher Support",
  },
  {
    slug: "emergency-lighting",
    title: "Emergency Lighting",
    eyebrow: "Safe evacuation when it matters most",
    intro: [
      "Emergency lighting is essential for helping people evacuate safely during a power failure, fire or emergency situation. It ensures escape routes, exits, stairwells and key safety areas remain visible when normal lighting fails.",
      "DM Fire & Security designs, installs, tests and maintains emergency lighting systems for residential, commercial and managed properties.",
    ],
    leadImage: "/fire-systems-card.png",
    leadAlt: "Emergency exit lighting and safety equipment",
    sectionTitle: "Safe evacuation when it matters most",
    sectionBody: [
      "In an emergency, clear visibility can make a critical difference. Emergency lighting helps guide occupants safely through escape routes and towards exits, reducing confusion and improving safety during evacuation.",
      "Our systems are designed to suit the layout, use and risk level of your property.",
    ],
    bulletsTitle: "Our emergency lighting services include",
    bullets: [
      "Emergency lighting design",
      "Emergency lighting installation",
      "Exit sign installation",
      "Escape route lighting installation",
      "Open area lighting installation",
      "High risk task lighting",
      "System commissioning",
      "Emergency lighting testing",
      "Maintenance and repairs",
      "Certification and documentation",
      "Compliance support",
    ],
    featuresTitle: "Emergency lighting systems we provide",
    features: [
      "Escape route lighting",
      "Open area emergency lighting",
      "High risk task area lighting",
      "Exit sign lighting",
      "Central battery systems",
      "Self contained emergency lights",
      "Maintained and non maintained lighting",
    ],
    suitableFor: [
      "Apartment blocks",
      "Offices and commercial premises",
      "Shops and retail units",
      "Schools and education buildings",
      "Care homes",
      "Warehouses and industrial sites",
      "Landlord managed properties",
      "Communal residential areas",
      "Hospitality and public access buildings",
    ],
    ctaTitle: "Keep your evacuation routes safe and compliant.",
    ctaText: "Contact DM Fire & Security today to arrange emergency lighting installation, testing or maintenance.",
    ctaButton: "Arrange Emergency Lighting Support",
  },
  {
    slug: "automatic-opening-ventilation",
    title: "Automatic Opening Ventilation",
    eyebrow: "Smoke control for safer escape routes",
    intro: [
      "Automatic Opening Ventilation systems, often known as AOV systems, are designed to help control smoke movement during a fire. These systems support safer evacuation by helping keep escape routes clearer and reducing smoke build up in key areas.",
      "DM Fire & Security designs, installs and maintains AOV systems for residential, commercial and managed buildings.",
    ],
    leadImage: "/fire-systems-card.png",
    leadAlt: "Ventilation and smoke control systems",
    sectionTitle: "Smoke control for safer escape routes",
    sectionBody: [
      "Smoke can spread quickly during a fire and create serious risks for occupants. AOV systems help ventilate smoke from stairwells, corridors, communal areas and smoke shafts, supporting safer evacuation and easier access for emergency services.",
      "Our AOV solutions can be integrated with fire alarm systems so vents open automatically when required.",
    ],
    bulletsTitle: "Our AOV services include",
    bullets: [
      "AOV system design",
      "Automatic vent installation",
      "Window actuator installation",
      "Roof hatch and louvre vent installation",
      "Smoke shaft system installation",
      "Integration with fire alarm systems",
      "System commissioning",
      "AOV testing and servicing",
      "Fault finding and repairs",
      "Maintenance and compliance documentation",
    ],
    featuresTitle: "AOV systems we provide",
    features: [
      "Window opening systems",
      "Roof hatch ventilation systems",
      "Louvre vent systems",
      "Smoke shaft systems",
      "Stairwell ventilation systems",
      "Communal area ventilation",
      "Fire alarm integrated AOV systems",
    ],
    suitableFor: [
      "Apartment blocks",
      "Stairwells and communal areas",
      "Commercial buildings",
      "Managed residential properties",
      "Care facilities",
      "Offices and mixed use buildings",
      "Schools and public buildings",
      "Buildings with smoke shaft systems",
    ],
    ctaTitle: "Need a reliable AOV system installed or maintained?",
    ctaText: "Contact DM Fire & Security today to discuss your smoke ventilation requirements.",
    ctaButton: "Discuss AOV Requirements",
  },
  {
    slug: "nurse-call-emergency-communication",
    title: "Nurse Call & Emergency Communication",
    eyebrow: "Fast communication in safety critical environments",
    intro: [
      "Nurse call and emergency communication systems help ensure assistance can be requested quickly when it is needed most. These systems are especially important in care environments, assisted living facilities, healthcare settings and buildings where vulnerable occupants may require support.",
      "DM Fire & Security designs, installs and maintains reliable emergency communication systems for residential and commercial properties.",
    ],
    leadImage: "/security-card.png",
    leadAlt: "Emergency communication and control systems",
    sectionTitle: "Fast communication in safety critical environments",
    sectionBody: [
      "A well designed nurse call or emergency communication system provides reassurance for residents, patients, staff and building users. It allows calls for help to be made quickly from key locations and ensures staff can respond efficiently.",
      "We provide wired, wireless and integrated systems depending on the needs of your property.",
    ],
    bulletsTitle: "Our services include",
    bullets: [
      "System design and planning",
      "Nurse call installation",
      "Pull cord and call point installation",
      "Staff alert panel setup",
      "Pager system installation",
      "Disabled refuge system installation",
      "EVC system installation",
      "Integration with fire and security systems",
      "System testing and commissioning",
      "Maintenance and repairs",
      "Certification and documentation",
    ],
    featuresTitle: "Systems we provide",
    features: [
      "Nurse call systems",
      "Bedside call units",
      "Pull cord systems",
      "Wall mounted call points",
      "Staff alert panels",
      "Pager systems",
      "Disabled refuge systems",
      "Emergency voice communication systems",
      "Integrated fire and security communication systems",
    ],
    suitableFor: [
      "Care homes",
      "Assisted living facilities",
      "Healthcare environments",
      "Residential buildings",
      "Disabled refuge areas",
      "Commercial premises",
      "Public buildings",
      "Managed properties",
    ],
    ctaTitle: "Improve safety and communication across your property.",
    ctaText: "Contact DM Fire & Security today to arrange a nurse call or emergency communication system survey.",
    ctaButton: "Arrange a Communication Survey",
  },
  {
    slug: "pa-speaker-systems",
    title: "PA & Speaker Systems",
    eyebrow: "Clear audio across your property",
    intro: [
      "Clear communication is essential in many buildings, especially in commercial, public access and managed environments. PA and speaker systems allow announcements, alerts, background audio and important messages to be delivered clearly across your property.",
      "DM Fire & Security designs, installs and maintains PA and speaker systems for residential, commercial and public environments.",
    ],
    leadImage: "/security-card.png",
    leadAlt: "PA system and speaker controls",
    sectionTitle: "Clear audio across your property",
    sectionBody: [
      "A professionally designed speaker system ensures sound is clear, balanced and suitable for the space. Whether you need a public address system, background music, zoned audio or emergency announcement capability, we can install a system that works reliably and is easy to control.",
    ],
    bulletsTitle: "Our services include",
    bullets: [
      "PA system design",
      "Speaker layout planning",
      "Speaker installation",
      "Amplifier and control equipment setup",
      "Zoned audio configuration",
      "Public address microphone setup",
      "Background music system installation",
      "Integration with fire alarms and EVC systems",
      "Testing and setup",
      "Maintenance and repairs",
    ],
    featuresTitle: "PA and speaker systems we provide",
    features: [
      "Public address systems",
      "Voice announcement systems",
      "Background music systems",
      "Zoned audio systems",
      "Wall mounted speakers",
      "Ceiling speakers",
      "Outdoor speakers",
      "Amplifier and control systems",
      "Integration with fire and emergency systems",
    ],
    suitableFor: [
      "Offices and commercial buildings",
      "Retail shops and shopping areas",
      "Schools and education facilities",
      "Hospitality venues",
      "Communal residential buildings",
      "Warehouses and industrial sites",
      "Care environments",
      "Public access buildings",
    ],
    ctaTitle: "Need clear and reliable audio across your property?",
    ctaText: "Contact DM Fire & Security today to discuss PA and speaker system installation.",
    ctaButton: "Discuss PA & Speaker Systems",
  },
  {
    slug: "certification-compliance",
    title: "Certification & Compliance",
    eyebrow: "Clear documentation for safer buildings",
    intro: [
      "Keeping your fire, electrical and safety systems properly tested, certified and documented is essential for responsible property management. DM Fire & Security provides professional certification and compliance support for residential, commercial and managed properties.",
      "We help landlords, businesses, facilities managers and property owners maintain clear records and confidence in their safety systems.",
    ],
    leadImage: "/fire-systems-card.png",
    leadAlt: "Fire safety documentation and certification support",
    sectionTitle: "Clear documentation for safer buildings",
    sectionBody: [
      "Compliance is not only about having systems installed. It is also about ensuring they are tested, maintained and documented correctly. Our certification services provide clear records that support safety, accountability and ongoing property management.",
    ],
    bulletsTitle: "Our compliance support includes",
    bullets: [
      "Fire alarm testing and certification",
      "Emergency lighting testing and certification",
      "Electrical inspection documentation",
      "PAT testing reports",
      "Fire extinguisher maintenance records",
      "Service logs and inspection records",
      "Digital documentation support",
      "Compliance focused advice",
      "Scheduled maintenance planning",
    ],
    featuresTitle: "Certification services we provide",
    features: [
      "Fire alarm certificates",
      "Emergency lighting certificates",
      "Electrical certificates",
      "PAT testing reports",
      "Fire extinguisher servicing records",
      "Maintenance documentation",
      "Digital compliance records",
      "System inspection reports",
    ],
    suitableFor: [
      "Landlords",
      "Businesses",
      "Facilities managers",
      "Property managers",
      "Residential buildings",
      "Commercial premises",
      "Care homes",
      "Schools",
      "Offices and retail sites",
      "Managed property portfolios",
    ],
    ctaTitle: "Need your systems tested, certified or documented?",
    ctaText: "Contact DM Fire & Security today to arrange certification and compliance support.",
    ctaButton: "Request Compliance Support",
  },
];

export function getFireDetailPage(slug: string) {
  return fireDetailPages.find((page) => page.slug === slug);
}
