import type { PremiumServicePageData, PremiumServiceTheme } from "./components/FireAlarmPremiumPage";

export type ServiceGroupKey = "fire" | "security" | "emergency" | "smart" | "compliance";

export type ServiceGroup = {
  key: ServiceGroupKey;
  route: string;
  label: string;
  theme: PremiumServiceTheme;
  landing: PremiumServicePageData;
  pages: PremiumServicePageData[];
};

function makePage(page: PremiumServicePageData): PremiumServicePageData {
  return page;
}

const commonSuitableFor = [
  "Commercial buildings",
  "Residential developments",
  "Managed properties",
  "Offices and retail units",
  "Education and care environments",
  "Facilities management portfolios",
];

const firePages = [
  makePage({
    slug: "fire-alarm-systems",
    title: "Fire Alarm Systems",
    eyebrow: "Early warning & dependable detection",
    intro: [
      "Helix designs, installs and maintains fire alarm systems that provide early warning, dependable performance and compliance support for a wide range of buildings.",
      "From conventional systems to addressable installations, our team plans each system around the layout, usage and risk profile of your premises.",
    ],
    heroImage: "/fire-alarm-systems-service.png",
    heroAlt: "Helix fire alarm panel with alarm sounder, beacon, smoke detector and manual call point",
    sectionTitle: "Professional fire alarm installation",
    sectionBody: [
      "Every fire alarm system should be designed around the building, not forced into a one-size-fits-all package.",
      "We support survey, design, installation, commissioning, maintenance and clear documentation for long-term safety management.",
    ],
    servicesTitle: "Our fire alarm services include",
    services: [
      "Fire alarm design and planning",
      "Conventional fire alarm systems",
      "Addressable fire alarm systems",
      "Fire alarm panel installation",
      "Smoke and heat detector installation",
      "Manual call point installation",
      "Sounder and beacon installation",
      "Commissioning and certification",
      "Fault finding and repairs",
      "Scheduled servicing and maintenance",
    ],
    featureCards: [
      { title: "Conventional Systems", text: "Ideal for smaller buildings divided into detection zones.", icon: "target" },
      { title: "Addressable Systems", text: "Better device identification for larger or more complex sites.", icon: "network" },
      { title: "Maintenance", text: "Keep alarms tested, reliable and documented.", icon: "shield" },
    ],
    suitableFor: commonSuitableFor,
    ctaTitle: "Protect your property with a professionally installed fire alarm system.",
    ctaText: "Talk to Helix today and arrange a survey or quote.",
    ctaButton: "Request a Fire Alarm Survey",
  }),
  makePage({
    slug: "fire-extinguishers-supply-servicing",
    title: "Fire Extinguishers (Supply & Servicing)",
    eyebrow: "Correct extinguishers for the right risk",
    intro: [
      "Helix supplies, installs and services fire extinguishers for commercial, residential and managed properties.",
      "We help ensure the correct extinguisher types are positioned, maintained and documented for the risks within your building.",
    ],
    heroImage: "/fire-extinguishers-service.png",
    heroAlt: "Wall mounted water foam and CO2 fire extinguishers with safety signage in a commercial building",
    sectionTitle: "Extinguisher supply, placement and servicing",
    sectionBody: [
      "Different risks need different extinguisher types, so placement and selection matters.",
      "Our service covers supply, installation, commissioning, annual servicing, replacements, signage and maintenance records.",
    ],
    servicesTitle: "Our extinguisher services include",
    services: [
      "Water, foam, CO2, powder and wet chemical extinguishers",
      "Extinguisher supply and installation",
      "Commissioning and location planning",
      "Annual servicing and maintenance",
      "Refills and replacements",
      "Fire extinguisher signage",
      "Service records and documentation",
      "Basic user guidance",
    ],
    featureCards: [
      { title: "Right Type", text: "Extinguishers selected for the actual site risks.", icon: "target" },
      { title: "Right Place", text: "Visible, accessible and compliant positioning.", icon: "building" },
      { title: "Right Records", text: "Servicing and documentation kept clear.", icon: "clipboard" },
    ],
    suitableFor: commonSuitableFor,
    ctaTitle: "Need extinguishers supplied or serviced?",
    ctaText: "Book professional fire extinguisher support with Helix.",
    ctaButton: "Book Extinguisher Support",
  }),
  makePage({
    slug: "aov-smoke-ventilation-systems",
    title: "AOV (Smoke Ventilation) Systems",
    eyebrow: "Smoke control for safer escape routes",
    intro: [
      "Automatic Opening Ventilation systems help control smoke movement during a fire and support safer evacuation routes.",
      "Helix installs and maintains AOV and smoke ventilation systems for residential, commercial and managed buildings.",
    ],
    heroImage: "/automatic-opening-ventilation-service.png",
    heroAlt: "Automatic opening ventilation windows controlling smoke movement in a stairwell",
    sectionTitle: "Smoke ventilation that works with your fire strategy",
    sectionBody: [
      "AOV systems can support stairwells, corridors, communal areas and smoke shafts by helping smoke escape from key routes.",
      "We integrate AOV controls with fire alarm systems where required and maintain systems so they remain ready to operate.",
    ],
    servicesTitle: "Our AOV services include",
    services: [
      "AOV system design and installation",
      "Window actuator installation",
      "Roof hatch and louvre vent systems",
      "Smoke shaft ventilation",
      "Stairwell and communal area ventilation",
      "Fire alarm integration",
      "Testing, servicing and repairs",
      "Compliance documentation",
    ],
    featureCards: [
      { title: "Smoke Control", text: "Ventilation planned around escape routes.", icon: "building" },
      { title: "Integration", text: "Linked to fire alarm systems where needed.", icon: "network" },
      { title: "Maintenance", text: "Operational checks and service records.", icon: "shield" },
    ],
    suitableFor: commonSuitableFor,
    ctaTitle: "Need reliable AOV or smoke ventilation support?",
    ctaText: "Talk to Helix about your building and escape route requirements.",
    ctaButton: "Discuss AOV Requirements",
  }),
  makePage({
    slug: "fire-safety-signage",
    title: "Fire Safety Signage",
    eyebrow: "Clear routes, clear instructions",
    intro: [
      "Fire safety signage helps occupants understand escape routes, extinguisher locations and key safety instructions quickly.",
      "Helix supplies and positions practical signage as part of wider fire safety and compliance support.",
    ],
    heroImage: "/certification-compliance-service.png",
    heroAlt: "Fire safety inspection checklist with fire alarm emergency lighting and extinguisher equipment",
    sectionTitle: "Signage that supports safe evacuation and compliance",
    sectionBody: [
      "Effective signage should be visible, consistent and placed where it helps people make quick decisions.",
      "We review escape routes, equipment locations and building usage to recommend suitable fire safety signs.",
    ],
    servicesTitle: "Fire signage support includes",
    services: [
      "Fire exit signage",
      "Escape route direction signs",
      "Fire extinguisher identification signs",
      "Fire action notices",
      "Door and mandatory safety signs",
      "Signage placement reviews",
      "Replacement and refresh support",
      "Documentation for managed sites",
    ],
    featureCards: [
      { title: "Visible", text: "Signs placed where people need them.", icon: "target" },
      { title: "Consistent", text: "A clear approach across the building.", icon: "clipboard" },
      { title: "Compliant", text: "Support for safety records and reviews.", icon: "shield" },
    ],
    suitableFor: commonSuitableFor,
    ctaTitle: "Need fire safety signage reviewed or installed?",
    ctaText: "Helix can help make escape routes and equipment locations clearer.",
    ctaButton: "Review Fire Signage",
  }),
];

const securityPages = [
  makePage({
    slug: "cctv-surveillance",
    title: "CCTV Surveillance",
    eyebrow: "Visual coverage that supports real oversight",
    intro: [
      "CCTV surveillance helps clients monitor entrances, shared spaces, circulation routes and high-risk areas with better visibility.",
      "Helix designs, installs and maintains CCTV systems that are practical to manage and configured around your site.",
    ],
    heroImage: "/cctv-systems-service.png",
    heroAlt: "CCTV camera and monitoring screens covering a commercial site",
    sectionTitle: "CCTV designed around the building",
    sectionBody: [
      "Good CCTV depends on camera placement, recording strategy, access to footage and long-term maintenance.",
      "We plan systems around real operating needs so clients can review incidents and maintain better site visibility.",
    ],
    servicesTitle: "Our CCTV services include",
    services: [
      "Camera placement planning",
      "Internal and external CCTV",
      "Recording and storage setup",
      "Remote viewing configuration",
      "System upgrades",
      "Maintenance and fault support",
    ],
    featureCards: [
      { title: "Coverage", text: "Camera placement around real risk points.", icon: "target" },
      { title: "Review", text: "Recording configured for incident playback.", icon: "clipboard" },
      { title: "Support", text: "Maintenance and upgrade support over time.", icon: "shield" },
    ],
    suitableFor: commonSuitableFor,
    ctaTitle: "Need CCTV coverage designed around your site?",
    ctaText: "Book a CCTV review with Helix.",
    ctaButton: "Book a CCTV Review",
  }),
  makePage({
    slug: "intruder-alarms",
    title: "Intruder Alarms",
    eyebrow: "Detection built around the site",
    intro: [
      "Intruder alarm systems protect buildings during unoccupied periods and trigger clear alerts when access events occur.",
      "Helix installs and maintains alarm systems configured around entry points, risk areas and occupancy patterns.",
    ],
    heroImage: "/intruder-alarm-service.png",
    heroAlt: "Intruder alarm keypad motion detector and mobile app showing an armed system",
    sectionTitle: "Alarm systems configured for daily use",
    sectionBody: [
      "Every site has different access patterns, after-hours risks and internal zones.",
      "We design intruder alarms that are practical to arm, disarm, maintain and manage.",
    ],
    servicesTitle: "Intruder alarm support includes",
    services: [
      "System design and placement planning",
      "Keypad and detector installation",
      "Door contact and sensor setup",
      "Zoning aligned to building use",
      "Monitored and standalone systems",
      "Fault finding and maintenance",
    ],
    featureCards: [
      { title: "Detection", text: "Movement and access events covered.", icon: "target" },
      { title: "Zoning", text: "Configured around how the building works.", icon: "network" },
      { title: "Support", text: "Servicing and fault response available.", icon: "shield" },
    ],
    suitableFor: commonSuitableFor,
    ctaTitle: "Need a more dependable intruder alarm setup?",
    ctaText: "Arrange an alarm review with Helix.",
    ctaButton: "Arrange an Alarm Review",
  }),
  makePage({
    slug: "access-control",
    title: "Access Control",
    eyebrow: "Manage who can enter and when",
    intro: [
      "Access control helps clients manage entry across staff doors, communal areas, restricted spaces and managed buildings.",
      "Helix installs and maintains access systems that improve day-to-day control while keeping entry simple for authorised users.",
    ],
    heroImage: "/security-card.png",
    heroAlt: "Access control and card reader equipment",
    sectionTitle: "Access control that supports safer operations",
    sectionBody: [
      "From staff-only zones to communal residential doors, access systems help reduce unauthorised entry.",
      "We focus on practical placement, permissions and administration so systems stay easy to manage.",
    ],
    servicesTitle: "Access control services include",
    services: [
      "Door entry systems",
      "Fob and card reader access",
      "Keypad access systems",
      "Maglocks and door hardware",
      "Permissions setup",
      "Servicing and repairs",
    ],
    featureCards: [
      { title: "Control", text: "Manage entry by person, area or time.", icon: "shield" },
      { title: "Visibility", text: "Better oversight of access points.", icon: "target" },
      { title: "Flexible", text: "Systems designed around the building.", icon: "network" },
    ],
    suitableFor: commonSuitableFor,
    ctaTitle: "Need better control over building access?",
    ctaText: "Talk to Helix about access control options.",
    ctaButton: "Discuss Access Control",
  }),
  makePage({
    slug: "intercom-systems",
    title: "Intercom Systems",
    eyebrow: "Clear communication at the entrance",
    intro: [
      "Intercom systems help staff, residents and visitors communicate clearly before access is granted.",
      "Helix supplies, installs and maintains intercom solutions for commercial, residential and managed properties.",
    ],
    heroImage: "/security-card.png",
    heroAlt: "Security control devices and intercom access equipment",
    sectionTitle: "Intercoms for safer, smoother entry",
    sectionBody: [
      "A good intercom system should be simple to use, reliable and positioned around how people enter the building.",
      "We support audio, video and access-linked intercom setups for a range of property types.",
    ],
    servicesTitle: "Intercom support includes",
    services: [
      "Audio intercom installation",
      "Video intercom installation",
      "Door entry integration",
      "Handset and panel replacement",
      "Fault finding and repairs",
      "Maintenance support",
    ],
    featureCards: [
      { title: "Clear", text: "Improve communication before access.", icon: "support" },
      { title: "Secure", text: "Support controlled entry decisions.", icon: "shield" },
      { title: "Reliable", text: "Maintained for daily use.", icon: "clipboard" },
    ],
    suitableFor: commonSuitableFor,
    ctaTitle: "Need an intercom system installed or upgraded?",
    ctaText: "Helix can review your entrance and access needs.",
    ctaButton: "Discuss Intercoms",
  }),
  makePage({
    slug: "gate-automation",
    title: "Gate Automation",
    eyebrow: "Controlled access for external entrances",
    intro: [
      "Gate automation supports safer, more convenient access control for car parks, private entrances and managed sites.",
      "Helix helps clients plan, install and maintain gate access solutions that integrate with wider security systems where required.",
    ],
    heroImage: "/cctv-systems-service.png",
    heroAlt: "Commercial site entrance with security monitoring and access control",
    sectionTitle: "Automated access that supports secure movement",
    sectionBody: [
      "Automated gates need to be safe, reliable and appropriate for the way vehicles and pedestrians use the site.",
      "We help plan access methods, safety controls and maintenance routines around the property.",
    ],
    servicesTitle: "Gate automation support includes",
    services: [
      "Gate automation planning",
      "Access control integration",
      "Intercom integration",
      "Safety device checks",
      "Maintenance and repairs",
      "Fault finding support",
    ],
    featureCards: [
      { title: "Controlled", text: "Manage vehicle access more consistently.", icon: "shield" },
      { title: "Integrated", text: "Connect gates with access systems.", icon: "network" },
      { title: "Maintained", text: "Support safe, reliable operation.", icon: "clipboard" },
    ],
    suitableFor: commonSuitableFor,
    ctaTitle: "Need gate automation support?",
    ctaText: "Talk to Helix about your entrance, site and access requirements.",
    ctaButton: "Discuss Gate Automation",
  }),
];

const emergencyPages = [
  makePage({
    slug: "emergency-lighting",
    title: "Emergency Lighting",
    eyebrow: "Safe evacuation when it matters most",
    intro: [
      "Emergency lighting keeps escape routes, exits and key safety areas visible when normal lighting fails.",
      "Helix designs, installs, tests and maintains emergency lighting systems for residential, commercial and managed properties.",
    ],
    heroImage: "/emergency-lighting-service.png",
    heroAlt: "Emergency lighting illuminating a safe evacuation route in a stairwell",
    sectionTitle: "Emergency lighting for safe evacuation",
    sectionBody: [
      "Clear visibility can make a critical difference in an emergency.",
      "We assess escape routes, open areas, stairwells and high-risk task areas to position lighting where it supports safe movement.",
    ],
    servicesTitle: "Emergency lighting services include",
    services: [
      "Emergency lighting design",
      "Escape route lighting",
      "Open area lighting",
      "Exit sign installation",
      "Testing and maintenance",
      "Certification and documentation",
    ],
    featureCards: [
      { title: "Visible", text: "Routes remain clearer during power loss.", icon: "target" },
      { title: "Tested", text: "Regular testing and records.", icon: "clipboard" },
      { title: "Supported", text: "Maintenance and repair support.", icon: "shield" },
    ],
    suitableFor: commonSuitableFor,
    ctaTitle: "Keep evacuation routes safe and compliant.",
    ctaText: "Arrange emergency lighting support with Helix.",
    ctaButton: "Arrange Emergency Lighting Support",
  }),
  makePage({
    slug: "emergency-voice-communication-evc",
    title: "Emergency Voice Communication (EVC)",
    eyebrow: "Reliable communication in emergency conditions",
    intro: [
      "Emergency Voice Communication systems help building users and response teams communicate during incidents.",
      "Helix installs and maintains EVC systems for refuge areas, managed buildings and safety-critical environments.",
    ],
    heroImage: "/nurse-call-emergency-communication-service.png",
    heroAlt: "Emergency communication control panel with wall speaker in a commercial building",
    sectionTitle: "EVC systems for safer response",
    sectionBody: [
      "Emergency communication systems must be simple, reliable and positioned around the response process.",
      "We support design, installation, commissioning and maintenance for EVC and disabled refuge communication systems.",
    ],
    servicesTitle: "EVC support includes",
    services: [
      "EVC system design",
      "Disabled refuge communication",
      "Outstation installation",
      "Control panel setup",
      "Testing and commissioning",
      "Maintenance and repairs",
    ],
    featureCards: [
      { title: "Clear", text: "Communication when it matters most.", icon: "support" },
      { title: "Reliable", text: "Systems tested and maintained.", icon: "shield" },
      { title: "Documented", text: "Service records for managed sites.", icon: "clipboard" },
    ],
    suitableFor: commonSuitableFor,
    ctaTitle: "Need emergency communication support?",
    ctaText: "Talk to Helix about EVC installation or maintenance.",
    ctaButton: "Discuss EVC Systems",
  }),
  makePage({
    slug: "nurse-call-systems",
    title: "Nurse Call Systems",
    eyebrow: "Fast support requests in care environments",
    intro: [
      "Nurse call systems help residents, patients and building users request assistance quickly.",
      "Helix designs, installs and maintains nurse call systems for care, assisted living and safety-critical environments.",
    ],
    heroImage: "/nurse-call-emergency-communication-service.png",
    heroAlt: "Emergency communication control panel with wall speaker in a commercial building",
    sectionTitle: "Nurse call systems designed around response",
    sectionBody: [
      "A nurse call system must be simple for users and efficient for staff to manage.",
      "We plan call points, staff alerts and control panels around the building, users and response process.",
    ],
    servicesTitle: "Nurse call support includes",
    services: [
      "Nurse call system installation",
      "Pull cord and call point installation",
      "Staff alert panels",
      "Pager system support",
      "Testing and maintenance",
      "Repairs and documentation",
    ],
    featureCards: [
      { title: "Responsive", text: "Help requests routed quickly.", icon: "support" },
      { title: "Practical", text: "Designed around staff workflows.", icon: "network" },
      { title: "Maintained", text: "Regular testing and support.", icon: "shield" },
    ],
    suitableFor: commonSuitableFor,
    ctaTitle: "Need a nurse call system installed or maintained?",
    ctaText: "Helix can help plan a dependable communication setup.",
    ctaButton: "Discuss Nurse Call",
  }),
  makePage({
    slug: "emergency-escape-route-signage",
    title: "Emergency & Escape Route Signage",
    eyebrow: "Clear direction during evacuation",
    intro: [
      "Emergency and escape route signage helps occupants understand where to go quickly during an incident.",
      "Helix reviews, supplies and positions signage for evacuation routes, exits and safety-critical areas.",
    ],
    heroImage: "/emergency-lighting-service.png",
    heroAlt: "Emergency exit route signage and lighting in a stairwell",
    sectionTitle: "Signage that supports safe movement",
    sectionBody: [
      "Escape route signage should be consistent, visible and easy to understand under pressure.",
      "We help make routes clearer for occupants while supporting the building’s wider safety management.",
    ],
    servicesTitle: "Signage support includes",
    services: [
      "Escape route signs",
      "Emergency exit signs",
      "Directional signage",
      "Fire action notices",
      "Signage placement reviews",
      "Replacement signage",
    ],
    featureCards: [
      { title: "Clear", text: "Simple guidance for safer evacuation.", icon: "target" },
      { title: "Consistent", text: "A joined-up approach across sites.", icon: "clipboard" },
      { title: "Supported", text: "Installed alongside safety reviews.", icon: "shield" },
    ],
    suitableFor: commonSuitableFor,
    ctaTitle: "Need emergency route signage support?",
    ctaText: "Helix can review and improve route clarity across your building.",
    ctaButton: "Review Escape Signage",
  }),
];

const smartPages = [
  makePage({
    slug: "smart-home-automation",
    title: "Smart Home Automation",
    eyebrow: "Connected control for modern properties",
    intro: [
      "Smart automation helps homes and managed spaces control lighting, access, security and everyday systems more easily.",
      "Helix plans and installs practical smart systems that are reliable, maintainable and appropriate for the property.",
    ],
    heroImage: "/hero-helix-security.png",
    heroAlt: "Helix engineer supporting modern smart building systems",
    sectionTitle: "Smart systems designed around daily use",
    sectionBody: [
      "Automation should make a property easier to manage, not harder.",
      "We focus on dependable setup, clear controls and integration with security or access systems where useful.",
    ],
    servicesTitle: "Automation support includes",
    services: [
      "Smart control planning",
      "Lighting and access integration",
      "App-based control setup",
      "Device configuration",
      "Network-aware installation",
      "Maintenance support",
    ],
    featureCards: [
      { title: "Connected", text: "Useful controls in one clear setup.", icon: "network" },
      { title: "Practical", text: "Automation matched to the property.", icon: "target" },
      { title: "Supported", text: "Configured for reliable use.", icon: "shield" },
    ],
    suitableFor: commonSuitableFor,
    ctaTitle: "Need smart automation for your property?",
    ctaText: "Talk to Helix about a practical connected setup.",
    ctaButton: "Discuss Smart Automation",
  }),
  makePage({
    slug: "wi-fi-network-ip-solutions",
    title: "Wi-Fi, Network & IP Solutions",
    eyebrow: "Reliable connectivity for connected systems",
    intro: [
      "Security, access and smart systems rely on dependable connectivity.",
      "Helix supports Wi-Fi, network and IP solutions that help building systems communicate reliably.",
    ],
    heroImage: "/security-card.png",
    heroAlt: "Security and network control equipment in a modern building",
    sectionTitle: "Connectivity that supports your systems",
    sectionBody: [
      "From CCTV remote viewing to smart controls and IP-based access systems, connectivity matters.",
      "We help plan practical network support for the systems that keep your property operating smoothly.",
    ],
    servicesTitle: "Network support includes",
    services: [
      "Wi-Fi planning support",
      "IP device configuration",
      "Network points and connectivity",
      "CCTV and access network support",
      "Remote viewing setup",
      "Fault finding support",
    ],
    featureCards: [
      { title: "Connected", text: "Support for IP-enabled systems.", icon: "network" },
      { title: "Reliable", text: "Configured for stable operation.", icon: "shield" },
      { title: "Practical", text: "Planned around building use.", icon: "target" },
    ],
    suitableFor: commonSuitableFor,
    ctaTitle: "Need Wi-Fi or IP system support?",
    ctaText: "Helix can help connect and configure your building systems.",
    ctaButton: "Discuss Network Support",
  }),
  makePage({
    slug: "minor-electrical-works",
    title: "Minor Electrical Works",
    eyebrow: "Supporting safe system installation",
    intro: [
      "Minor electrical works often support fire, security, emergency and smart system installations.",
      "Helix provides practical electrical support where required as part of joined-up building system delivery.",
    ],
    heroImage: "/compliance-service-card.png",
    heroAlt: "Compliance and building system support materials",
    sectionTitle: "Electrical support for safer installations",
    sectionBody: [
      "Small electrical works can be essential for neat, safe and reliable system installation.",
      "We coordinate minor works alongside the wider system delivery so projects stay simpler for clients.",
    ],
    servicesTitle: "Minor works support includes",
    services: [
      "Power support for system equipment",
      "Accessory replacement",
      "Minor wiring works",
      "Safe installation support",
      "Testing and documentation",
      "Fault support",
    ],
    featureCards: [
      { title: "Neat", text: "Support for clean installation.", icon: "building" },
      { title: "Safe", text: "Work completed with safety in mind.", icon: "shield" },
      { title: "Joined-up", text: "Coordinated with system delivery.", icon: "network" },
    ],
    suitableFor: commonSuitableFor,
    ctaTitle: "Need minor electrical support with your systems?",
    ctaText: "Talk to Helix about your installation requirements.",
    ctaButton: "Discuss Minor Works",
  }),
  makePage({
    slug: "portable-appliance-testing-pat",
    title: "Portable Appliance Testing (PAT)",
    eyebrow: "Practical testing and clear records",
    intro: [
      "Portable Appliance Testing helps organisations keep electrical equipment checks organised and documented.",
      "Helix supports PAT testing for offices, managed buildings, commercial environments and property portfolios.",
    ],
    heroImage: "/certification-compliance-service.png",
    heroAlt: "Safety inspection checklist and compliance equipment",
    sectionTitle: "PAT testing that supports organised records",
    sectionBody: [
      "PAT testing should be clear, practical and easy to evidence.",
      "We help clients keep testing records up to date as part of wider compliance and maintenance support.",
    ],
    servicesTitle: "PAT support includes",
    services: [
      "Portable appliance testing",
      "Equipment labelling",
      "Test records",
      "Asset list support",
      "Failed item reporting",
      "Planned retesting schedules",
    ],
    featureCards: [
      { title: "Tested", text: "Equipment checks completed clearly.", icon: "check" },
      { title: "Documented", text: "Records ready for management review.", icon: "clipboard" },
      { title: "Planned", text: "Support for recurring schedules.", icon: "shield" },
    ],
    suitableFor: commonSuitableFor,
    ctaTitle: "Need PAT testing for your property or portfolio?",
    ctaText: "Helix can help keep appliance testing organised.",
    ctaButton: "Book PAT Testing",
  }),
];

const compliancePages = [
  makePage({
    slug: "certification-compliance",
    title: "Certification & Compliance",
    eyebrow: "Clear documentation for safer buildings",
    intro: [
      "Keeping fire, electrical and safety systems properly tested, certified and documented is essential for responsible property management.",
      "Helix provides practical certification and compliance support for landlords, businesses, facilities managers and property owners.",
    ],
    heroImage: "/certification-compliance-service.png",
    heroAlt: "Fire safety inspection checklist with fire alarm emergency lighting and extinguisher equipment",
    sectionTitle: "Clear documentation for safer buildings",
    sectionBody: [
      "Compliance is not only about having systems installed. It is about ensuring they are tested, maintained and documented correctly.",
      "Our certification support provides clear records for safety, accountability and ongoing property management.",
    ],
    servicesTitle: "Certification support includes",
    services: [
      "Fire alarm testing records",
      "Emergency lighting certificates",
      "Fire extinguisher service records",
      "Maintenance documentation",
      "Digital compliance records",
      "Inspection reports",
    ],
    featureCards: [
      { title: "Clear", text: "Documentation that is easier to manage.", icon: "clipboard" },
      { title: "Planned", text: "Support for recurring testing cycles.", icon: "network" },
      { title: "Accountable", text: "One team across system records.", icon: "shield" },
    ],
    suitableFor: commonSuitableFor,
    ctaTitle: "Need your systems tested, certified or documented?",
    ctaText: "Arrange certification and compliance support with Helix.",
    ctaButton: "Book Compliance Support",
  }),
  makePage({
    slug: "safety-inspections-testing",
    title: "Safety Inspections & Testing",
    eyebrow: "Inspections that keep risks visible",
    intro: [
      "Regular inspections and testing help identify faults, gaps and maintenance needs before they become bigger issues.",
      "Helix supports planned safety inspections across fire, emergency, security and electrical support services.",
    ],
    heroImage: "/certification-compliance-service.png",
    heroAlt: "Engineer completing a fire safety inspection checklist",
    sectionTitle: "Testing and inspection support for managed properties",
    sectionBody: [
      "A well-managed building needs inspection routines that are practical and clearly recorded.",
      "We help clients keep evidence, findings and next steps organised.",
    ],
    servicesTitle: "Inspection support includes",
    services: [
      "Fire alarm inspections",
      "Emergency lighting tests",
      "Extinguisher checks",
      "AOV operational checks",
      "Security system inspections",
      "Report and record support",
    ],
    featureCards: [
      { title: "Visible", text: "Find issues before they escalate.", icon: "target" },
      { title: "Recorded", text: "Clear reports and actions.", icon: "clipboard" },
      { title: "Reliable", text: "Support for planned maintenance.", icon: "shield" },
    ],
    suitableFor: commonSuitableFor,
    ctaTitle: "Need safety inspections or system testing?",
    ctaText: "Helix can support planned checks and reporting.",
    ctaButton: "Book Safety Testing",
  }),
  makePage({
    slug: "regulatory-compliance-services",
    title: "Regulatory Compliance Services",
    eyebrow: "Practical support for building responsibilities",
    intro: [
      "Regulatory compliance can feel fragmented when fire, security, emergency systems and records are managed separately.",
      "Helix helps bring responsibilities, maintenance and documentation into a clearer service model.",
    ],
    heroImage: "/compliance-service-card.png",
    heroAlt: "Compliance records and certification support materials",
    sectionTitle: "Compliance support with one accountable team",
    sectionBody: [
      "Our role is to help clients understand what needs attention, what has been completed and how records should be maintained.",
      "We support landlords, facilities teams and managed portfolios with practical, ongoing compliance-led service.",
    ],
    servicesTitle: "Regulatory support includes",
    services: [
      "Compliance gap reviews",
      "Maintenance planning",
      "Service documentation",
      "Testing schedules",
      "Portfolio reporting",
      "Fire and security record support",
    ],
    featureCards: [
      { title: "Joined-up", text: "Fire, security and compliance aligned.", icon: "network" },
      { title: "Practical", text: "Clear recommendations and actions.", icon: "target" },
      { title: "Documented", text: "Records that support accountability.", icon: "clipboard" },
    ],
    suitableFor: commonSuitableFor,
    ctaTitle: "Need clearer regulatory compliance support?",
    ctaText: "Talk to Helix about your responsibilities and record keeping.",
    ctaButton: "Book a Compliance Review",
  }),
];

function makeLanding(
  group: string,
  slug: string,
  title: string,
  eyebrow: string,
  intro: string[],
  heroImage: string,
  pages: PremiumServicePageData[],
): PremiumServicePageData {
  return {
    slug,
    title,
    eyebrow,
    intro,
    heroImage,
    heroAlt: `${title} services from Helix`,
    sectionTitle: `Complete ${group.toLowerCase()} support for your property`,
    sectionBody: [
      "Every building has different risks, usage patterns and responsibilities. Helix reviews your property carefully and recommends practical systems and support that fit the way the site operates.",
      "Our team keeps the process clear from survey and design through installation, maintenance and documentation.",
    ],
    servicesTitle: `Explore ${group.toLowerCase()} services`,
    services: pages.map((page) => page.title),
    featureCards: pages.slice(0, 3).map((page, index) => ({
      title: page.title,
      text: page.eyebrow,
      icon: ["target", "network", "shield"][index] ?? "shield",
    })),
    suitableFor: commonSuitableFor,
    ctaTitle: `Need ${group.toLowerCase()} support for your building?`,
    ctaText: "Talk to Helix today and we will help shape the right next step.",
    ctaButton: "Book a Survey",
  };
}

export const serviceGroups: Record<ServiceGroupKey, ServiceGroup> = {
  fire: {
    key: "fire",
    route: "/fire-systems",
    label: "Fire Systems",
    theme: { category: "Fire Systems", categoryHref: "/fire-systems", accent: "#EF2B2D", accentDark: "#B91C1C", label: "Fire" },
    landing: makeLanding("Fire Systems", "fire-systems", "Fire Systems", "Complete fire protection support", [
      "Helix provides fire systems that protect people, property and day-to-day operations.",
      "From alarms and extinguishers to smoke ventilation and signage, our team delivers practical fire safety support.",
    ], "/fire-systems-card.png", firePages),
    pages: firePages,
  },
  security: {
    key: "security",
    route: "/security",
    label: "Security Systems",
    theme: { category: "Security Systems", categoryHref: "/security", accent: "#2855C7", accentDark: "#1D3F99", label: "Security" },
    landing: makeLanding("Security Systems", "security", "Security Systems", "Protection, access and monitoring", [
      "Helix designs, installs and maintains security systems that improve visibility, controlled access and response planning.",
      "Our solutions are configured around the way your property is used, occupied and managed.",
    ], "/security-card.png", securityPages),
    pages: securityPages,
  },
  emergency: {
    key: "emergency",
    route: "/emergency-systems",
    label: "Emergency Systems",
    theme: { category: "Emergency Systems", categoryHref: "/emergency-systems", accent: "#EF2B2D", accentDark: "#B91C1C", label: "Emergency" },
    landing: makeLanding("Emergency Systems", "emergency-systems", "Emergency Systems", "Safe response when it matters", [
      "Helix supports emergency systems that help people evacuate, communicate and request support quickly.",
      "From emergency lighting and EVC to nurse call and escape route signage, we keep safety-critical systems clear and reliable.",
    ], "/emergency-lighting-service.png", emergencyPages),
    pages: emergencyPages,
  },
  smart: {
    key: "smart",
    route: "/smart-systems",
    label: "Smart Systems",
    theme: { category: "Smart Systems", categoryHref: "/smart-systems", accent: "#2855C7", accentDark: "#1D3F99", label: "Smart" },
    landing: makeLanding("Smart Systems", "smart-systems", "Smart Systems", "Connected building support", [
      "Helix supports smart, networked and electrical services that help modern properties operate more smoothly.",
      "We focus on practical systems that are reliable, maintainable and easy for clients to manage.",
    ], "/hero-helix-security.png", smartPages),
    pages: smartPages,
  },
  compliance: {
    key: "compliance",
    route: "/compliance",
    label: "Compliance",
    theme: { category: "Compliance", categoryHref: "/compliance", accent: "#198754", accentDark: "#11683F", label: "Compliance" },
    landing: makeLanding("Compliance", "compliance", "Compliance", "Certification, inspections and records", [
      "Helix helps clients keep fire, security, emergency and electrical safety responsibilities clearer and better documented.",
      "Our compliance support is designed for property owners, landlords, facilities teams and managed portfolios.",
    ], "/compliance-service-card.png", compliancePages),
    pages: compliancePages,
  },
};

export function getServiceGroup(key: ServiceGroupKey) {
  return serviceGroups[key];
}

export function getServicePage(key: ServiceGroupKey, slug: string) {
  return serviceGroups[key].pages.find((page) => page.slug === slug);
}
