export type InfoPageLink = {
  label: string;
  href: string;
};

export type InfoPageData = {
  slug: string;
  title: string;
  eyebrow: string;
  intro: string[];
  image: string;
  imageAlt: string;
  metrics: { value: string; label: string }[];
  overviewTitle: string;
  overview: string[];
  highlightsTitle: string;
  highlights: string[];
  gridTitle: string;
  gridIntro: string;
  gridItems: { title: string; text: string; href?: string }[];
  fitTitle: string;
  fitItems: string[];
  ctaTitle: string;
  ctaText: string;
  ctaButton: string;
};

export type SectionCollection = {
  section: string;
  landing: InfoPageData;
  pages: InfoPageData[];
};

function makePage(data: InfoPageData): InfoPageData {
  return data;
}

export const compliancePage: InfoPageData = makePage({
  slug: "compliance",
  title: "Compliance",
  eyebrow: "Documentation, reporting and accountability",
  intro: [
    "Helix supports property owners, landlords, facilities teams and managed portfolios with practical compliance support across fire safety, security systems and ongoing service records.",
    "Our role is to help clients keep systems tested, documented and easier to manage, with clear reporting, planned maintenance and one accountable team behind the work.",
  ],
  image: "/compliance-service-card.png",
  imageAlt: "Helix engineer and vehicle supporting compliance-led building services",
  metrics: [
    { value: "Clear", label: "Documentation and reporting" },
    { value: "Planned", label: "Testing and maintenance support" },
    { value: "Joined-up", label: "Fire and security oversight" },
  ],
  overviewTitle: "Compliance support built around real building responsibilities",
  overview: [
    "Compliance is not just about installing systems. It is about ensuring they remain tested, maintained and documented in a way that supports safe operation and easier property management.",
    "Helix helps clients stay organised with practical service records, recurring maintenance support and a clearer view of what has been completed, what needs attention and what should happen next.",
  ],
  highlightsTitle: "What our compliance support can include",
  highlights: [
    "Fire alarm testing and maintenance records",
    "Emergency lighting checks and certification support",
    "Fire extinguisher servicing documentation",
    "Security system servicing and inspection records",
    "Planned maintenance scheduling across sites",
    "Clear reporting for landlords, facilities managers and property teams",
  ],
  gridTitle: "Explore compliance-led support",
  gridIntro:
    "These pages and services help clients stay organised, reduce gaps in service oversight and keep fire and security responsibilities easier to manage over time.",
  gridItems: [
    {
      title: "Certification & Compliance",
      text: "Testing, certificates, service records and ongoing support for life-safety systems.",
      href: "/fire-systems/certification-compliance",
    },
    {
      title: "Your Responsibilities",
      text: "Understand the core responsibilities that sit behind safer buildings and better record keeping.",
      href: "/resources/your-responsibilities",
    },
    {
      title: "How We Work",
      text: "See how Helix delivers surveys, installations, maintenance and reporting through one accountable team.",
      href: "/about/how-we-work",
    },
    {
      title: "Integrated Support",
      text: "Bring fire systems, security and compliance conversations into one clearer service model.",
    },
  ],
  fitTitle: "Best suited to",
  fitItems: [
    "Landlords and managing agents",
    "Facilities and estates teams",
    "Commercial multi-site portfolios",
    "Residential blocks and communal buildings",
    "Care, education and public-use sites",
    "Clients needing clearer maintenance records",
  ],
  ctaTitle: "Need clearer support around compliance and documentation?",
  ctaText:
    "Talk to Helix about your current responsibilities, reporting gaps or maintenance planning and we will help shape the right next step.",
  ctaButton: "Book a Compliance Review",
});

export const aboutCollection: SectionCollection = {
  section: "about",
  landing: makePage({
    slug: "about",
    title: "About Helix",
    eyebrow: "One accountable team",
    intro: [
      "Helix Fire & Security delivers integrated fire, security and compliance support for buildings that need a dependable partner, not disconnected contractors.",
      "We work across residential, commercial and managed environments, supporting surveys, installations, servicing, reporting and reactive support through one coordinated team.",
    ],
    image: "/hero-helix-security.png",
    imageAlt: "Helix engineer securing a building entrance",
    metrics: [
      { value: "24/7", label: "Support coverage" },
      { value: "1 team", label: "Single accountable partner" },
      { value: "End-to-end", label: "Delivery from survey to support" },
    ],
    overviewTitle: "Built around clarity, delivery and long-term support",
    overview: [
      "Our approach is designed to remove friction from property management. We coordinate safety systems, servicing schedules, compliance records and communication so clients can work with one responsive partner.",
      "That means fewer handovers, better visibility across sites and a more consistent standard of service from planning through aftercare.",
    ],
    highlightsTitle: "What clients can expect",
    highlights: [
      "Clear surveys and practical recommendations",
      "Coordinated installation and commissioning",
      "Responsive maintenance and fault support",
      "Straightforward communication with accountable contacts",
      "Compliance-focused documentation and reporting",
      "Support across mixed property portfolios and managed estates",
    ],
    gridTitle: "Explore the way we work",
    gridIntro: "These pages explain how Helix delivers projects, supports clients and maintains standards across fire, security and compliance services.",
    gridItems: [
      { title: "How We Work", text: "Our delivery process from survey and design through installation, maintenance and reporting.", href: "/about/how-we-work" },
      { title: "Our Team", text: "The engineers, managers and support teams behind our nationwide delivery model.", href: "/about/our-team" },
      { title: "Environmental Commitments", text: "How we approach efficiency, responsible operations and long-term sustainability.", href: "/about/environmental-commitments" },
      { title: "Careers", text: "Join a team focused on technical quality, responsiveness and continued development.", href: "/about/careers" },
    ],
    fitTitle: "Ideal for",
    fitItems: [
      "Facilities managers",
      "Managing agents",
      "Landlords and developers",
      "Commercial occupiers",
      "Residential portfolios",
      "Care and education environments",
    ],
    ctaTitle: "Need a dependable team to support your buildings?",
    ctaText: "Talk to Helix about your current setup, service gaps or upcoming projects and we will help plan the next step.",
    ctaButton: "Speak to Helix",
  }),
  pages: [
    makePage({
      slug: "how-we-work",
      title: "How We Work",
      eyebrow: "Consultation to completion",
      intro: [
        "Helix delivers projects through a clear, staged process that keeps clients informed from first survey through installation, maintenance and reporting.",
        "We focus on practical recommendations, dependable delivery and a single line of accountability throughout the job.",
      ],
      image: "/hero-helix-security.png",
      imageAlt: "Helix service process in action",
      metrics: [
        { value: "Survey", label: "Initial discovery" },
        { value: "Install", label: "Coordinated delivery" },
        { value: "Maintain", label: "Ongoing support" },
      ],
      overviewTitle: "A structured process without unnecessary complexity",
      overview: [
        "We begin by understanding the property, its risks, the required standards and the practical needs of the people using the building every day.",
        "From there, we shape a scope that can be installed, maintained and documented in a way that supports both safety and long-term building management.",
      ],
      highlightsTitle: "Our delivery model includes",
      highlights: [
        "Site surveys and technical reviews",
        "System recommendations aligned to the building",
        "Installation planning and coordination",
        "Commissioning, testing and handover",
        "Planned servicing and reactive support",
        "Clear certification and reporting",
      ],
      gridTitle: "What good delivery looks like",
      gridIntro: "Every stage is designed to reduce delays, avoid confusion and make ongoing management easier for the client team.",
      gridItems: [
        { title: "Survey & review", text: "We assess layouts, risks, current systems and operational constraints before recommending the right route forward." },
        { title: "Design & scope", text: "Recommendations are shaped around what the building actually needs rather than a generic package." },
        { title: "Installation", text: "Engineers deliver systems with clear communication around access, timelines and handover requirements." },
        { title: "Aftercare", text: "Servicing, maintenance, reporting and support continue after installation so nothing is left unmanaged." },
      ],
      fitTitle: "Useful for",
      fitItems: [
        "Live environments needing phased works",
        "Managed residential blocks",
        "Multi-site commercial estates",
        "Properties with compliance deadlines",
        "Teams replacing multiple contractors with one provider",
      ],
      ctaTitle: "Want to review how your current service model is working?",
      ctaText: "We can help you compare your current setup against a more integrated delivery approach.",
      ctaButton: "Book a Service Review",
    }),
    makePage({
      slug: "our-team",
      title: "Our Team",
      eyebrow: "Engineers, managers and support",
      intro: [
        "Helix combines field engineers, technical managers, service coordinators and support teams so clients are backed by more than a single point of contact.",
        "That structure helps us deliver projects properly, keep service visits organised and give clients better visibility across the work being done.",
      ],
      image: "/security-card.png",
      imageAlt: "Team and support focused security environment",
      metrics: [
        { value: "Technical", label: "Engineers and specialists" },
        { value: "Coordinated", label: "Support and scheduling" },
        { value: "Responsive", label: "Client communication" },
      ],
      overviewTitle: "A team model designed to support delivery properly",
      overview: [
        "We believe quality comes from combining field experience with strong coordination behind the scenes. That means engineers are supported by managers and clients are supported by organised communication.",
        "The result is a service model that feels more stable, more informed and easier to manage across day-to-day operations.",
      ],
      highlightsTitle: "Core strengths across the team",
      highlights: [
        "Experienced fire and security engineers",
        "Technical managers for design and oversight",
        "Account support for communication and scheduling",
        "Documentation and compliance support",
        "Reactive fault response and servicing coordination",
        "Long-term client relationship management",
      ],
      gridTitle: "How the team supports clients",
      gridIntro: "Each role contributes to a smoother experience for the client, from planning and execution to reporting and follow-up.",
      gridItems: [
        { title: "Engineers", text: "Carry out installation, maintenance, fault diagnosis and technical support across live sites." },
        { title: "Technical managers", text: "Provide oversight, guidance and quality control across more complex or multi-stage scopes." },
        { title: "Support staff", text: "Help with coordination, documentation, visit planning and service communication." },
        { title: "Account contacts", text: "Keep clients informed and help ensure actions, timelines and records stay aligned." },
      ],
      fitTitle: "Best suited to",
      fitItems: [
        "Clients managing multiple stakeholders",
        "Sites needing dependable communication",
        "Properties with mixed safety systems",
        "Portfolios requiring recurring servicing",
      ],
      ctaTitle: "Need a more dependable support structure around your sites?",
      ctaText: "Talk to us about how Helix can support your properties with a more joined-up delivery team.",
      ctaButton: "Meet the Team",
    }),
    makePage({
      slug: "environmental-commitments",
      title: "Environmental Commitments",
      eyebrow: "Responsible operations",
      intro: [
        "Helix takes a practical approach to environmental responsibility, focusing on efficient operations, sensible planning and long-term system performance.",
        "For us, sustainability is not a standalone message. It sits inside the way projects are scoped, serviced and managed over time.",
      ],
      image: "/hero-helix-security.png",
      imageAlt: "Helix van and building environment at dusk",
      metrics: [
        { value: "Efficient", label: "Planned callouts" },
        { value: "Long-term", label: "Maintainable systems" },
        { value: "Practical", label: "Real operational decisions" },
      ],
      overviewTitle: "A practical sustainability mindset",
      overview: [
        "We look at environmental impact through the everyday decisions that shape service delivery: efficient routing, durable installations, fewer repeat visits and systems that are maintainable over time.",
        "That approach helps reduce waste while still keeping safety, compliance and responsiveness at the centre of the work.",
      ],
      highlightsTitle: "Our focus includes",
      highlights: [
        "Efficient scheduling and route planning",
        "Maintaining systems to extend useful life",
        "Reducing repeat attendances through better fixes",
        "Choosing practical, maintainable solutions",
        "Clear reporting that supports planned maintenance",
      ],
      gridTitle: "How this supports clients",
      gridIntro: "A practical environmental approach also helps reduce disruption, improve asset life and support better long-term budgeting.",
      gridItems: [
        { title: "Planned maintenance", text: "Helps reduce reactive failures and unnecessary repeat attendance." },
        { title: "Better fixes", text: "Focusing on durable outcomes means fewer avoidable issues returning later." },
        { title: "Smarter system choices", text: "Maintainable installations can support both operational and environmental goals over time." },
      ],
      fitTitle: "Relevant for",
      fitItems: [
        "Long-term property holders",
        "Managed estates",
        "Organisations with ESG priorities",
        "Clients looking to reduce operational waste",
      ],
      ctaTitle: "Need a service partner with a more practical long-term mindset?",
      ctaText: "We can support your buildings in a way that balances safety, performance and responsible delivery.",
      ctaButton: "Discuss Your Portfolio",
    }),
    makePage({
      slug: "careers",
      title: "Careers",
      eyebrow: "Grow with Helix",
      intro: [
        "Helix is built around quality delivery, responsive support and strong technical standards. That depends on bringing in people who care about doing the job properly.",
        "We welcome engineers, coordinators and support professionals who want to work in a team that values accountability, development and clear communication.",
      ],
      image: "/security-card.png",
      imageAlt: "Professional working environment",
      metrics: [
        { value: "Supportive", label: "Team culture" },
        { value: "Technical", label: "Growth-focused work" },
        { value: "Long-term", label: "Career development" },
      ],
      overviewTitle: "A workplace built around professionalism and progress",
      overview: [
        "We want people who take pride in the details, work well with clients and understand the importance of dependable service across safety-critical environments.",
        "In return, we aim to create a team culture with clear expectations, practical support and room to grow across technical and operational roles.",
      ],
      highlightsTitle: "Why join Helix",
      highlights: [
        "Work across meaningful fire and security projects",
        "Join a team focused on standards and delivery",
        "Build experience across varied building types",
        "Develop technical and client-facing skills",
        "Contribute to a growing integrated service model",
      ],
      gridTitle: "Typical opportunities",
      gridIntro: "Roles can vary across engineering, technical support, coordination and wider operational functions.",
      gridItems: [
        { title: "Engineering roles", text: "Installation, maintenance, fault-finding and reactive support across fire and security systems." },
        { title: "Service support", text: "Planning, coordination and helping clients stay informed across scheduled works." },
        { title: "Operational growth", text: "Opportunities to support quality, reporting and wider service delivery functions." },
      ],
      fitTitle: "Ideal for",
      fitItems: [
        "Fire and security engineers",
        "Technically minded support staff",
        "Service coordinators",
        "Professionals looking for long-term growth",
      ],
      ctaTitle: "Interested in working with Helix?",
      ctaText: "Send us your details and let us know what kind of role or opportunity you are looking for.",
      ctaButton: "Start a Careers Enquiry",
    }),
  ],
};

export const securityCollection: SectionCollection = {
  section: "security",
  landing: makePage({
    slug: "security",
    title: "Security Solutions",
    eyebrow: "Protecting people, property and access",
    intro: [
      "Helix designs, installs and maintains security systems that help clients protect buildings, control access and respond quickly when issues arise.",
      "From CCTV and intruder alarms to monitored systems and access control, we deliver security services that are practical to manage and appropriate for the site.",
    ],
    image: "/security-card.png",
    imageAlt: "Security control devices and CCTV hardware",
    metrics: [
      { value: "CCTV", label: "Visual coverage" },
      { value: "Access", label: "Controlled entry" },
      { value: "Alarm", label: "Detection and response" },
    ],
    overviewTitle: "Integrated security support for real operating environments",
    overview: [
      "Security systems need to work reliably in the context of the building, not just look good on paper. We focus on practical placement, intuitive operation and dependable maintenance.",
      "That helps clients manage daily access, improve visibility and maintain confidence in how the site is protected.",
    ],
    highlightsTitle: "Security priorities we support",
    highlights: [
      "Site visibility through CCTV",
      "Intruder detection and monitoring",
      "Controlled access for staff and visitors",
      "Better oversight across entrances and shared areas",
      "Reliable maintenance and fault response",
      "A consistent approach across mixed-site portfolios",
    ],
    gridTitle: "Our security services",
    gridIntro: "Each security service is tailored to the building, occupancy patterns and the level of oversight the client needs.",
    gridItems: [
      { title: "CCTV Systems", text: "Visible coverage and event review across entrances, shared spaces and key risk areas.", href: "/security/cctv-systems" },
      { title: "Intruder Alarm Monitoring", text: "Monitoring-led support that helps clients respond quickly when alarms activate.", href: "/security/intruder-alarm-monitoring" },
      { title: "Intruder Alarm", text: "Detection systems configured around the way the building is used day to day.", href: "/security/intruder-alarm" },
      { title: "Access Control Systems", text: "Practical entry management for staff, residents, visitors and managed environments.", href: "/security/access-control-systems" },
    ],
    fitTitle: "Suitable for",
    fitItems: [
      "Commercial premises",
      "Residential developments",
      "Mixed-use buildings",
      "Care and education sites",
      "Managed estates",
      "Facilities management portfolios",
    ],
    ctaTitle: "Need a more joined-up security setup for your property?",
    ctaText: "Talk to Helix about the level of coverage, access control or alarm support your site actually needs.",
    ctaButton: "Discuss Security Support",
  }),
  pages: [
    makePage({
      slug: "cctv-systems",
      title: "CCTV Systems",
      eyebrow: "Visual coverage that supports real oversight",
      intro: [
        "CCTV helps clients monitor entrances, shared spaces, circulation routes and high-risk areas with better visibility and clearer incident review.",
        "Helix designs, installs and maintains CCTV systems for buildings that need dependable coverage and straightforward day-to-day management.",
      ],
      image: "/security-card.png",
      imageAlt: "CCTV camera and security equipment",
      metrics: [
        { value: "Live view", label: "Better visibility" },
        { value: "Playback", label: "Review incidents" },
        { value: "Coverage", label: "Designed around the site" },
      ],
      overviewTitle: "CCTV designed around the building, not just the product",
      overview: [
        "Good CCTV depends on more than camera count. We look at entrances, circulation paths, blind spots, operational priorities and who needs access to footage or live views.",
        "That helps create a system that actually supports building management and incident review.",
      ],
      highlightsTitle: "Our CCTV service includes",
      highlights: [
        "Site reviews and camera placement planning",
        "Internal and external camera coverage",
        "Recording and storage configuration",
        "Remote viewing setup",
        "System upgrades and additional coverage",
        "Maintenance and fault support",
      ],
      gridTitle: "Typical CCTV priorities",
      gridIntro: "Most projects focus on visibility, reliability and the ability to retrieve footage quickly when something happens.",
      gridItems: [
        { title: "Entrances", text: "Monitor arrivals, exits and access events around key entry points." },
        { title: "Shared areas", text: "Improve oversight across corridors, reception spaces and communal zones." },
        { title: "Perimeter views", text: "Provide coverage across building exteriors, yards and vehicle approaches." },
        { title: "Operational review", text: "Support incident review with recording and playback configured to suit the site." },
      ],
      fitTitle: "Suitable for",
      fitItems: ["Offices", "Retail", "Residential blocks", "Car parks", "Shared commercial spaces", "Managed estates"],
      ctaTitle: "Need CCTV designed around the way your site actually operates?",
      ctaText: "We can help plan practical coverage, recording and support for your property.",
      ctaButton: "Book a CCTV Review",
    }),
    makePage({
      slug: "intruder-alarm-monitoring",
      title: "Intruder Alarm Monitoring",
      eyebrow: "Faster awareness when alarms activate",
      intro: [
        "Monitoring adds an extra layer of confidence by helping ensure alarm activations are not missed when a site is empty or operating with limited on-site presence.",
        "Helix supports monitored intruder alarm setups that improve awareness and response planning across managed buildings.",
      ],
      image: "/security-card.png",
      imageAlt: "Alarm keypad with security monitoring devices",
      metrics: [
        { value: "Always on", label: "Out-of-hours awareness" },
        { value: "Escalation", label: "Defined response routes" },
        { value: "Support", label: "System maintenance" },
      ],
      overviewTitle: "Monitoring that supports practical response planning",
      overview: [
        "A monitored setup only works properly when escalation paths, keyholder expectations and ongoing maintenance are all aligned.",
        "We help clients put those pieces together so monitoring supports the building rather than adding confusion.",
      ],
      highlightsTitle: "Monitoring support includes",
      highlights: [
        "Monitoring-ready alarm configuration",
        "Signal path and communication setup",
        "Keyholder and escalation planning",
        "System testing and reliability checks",
        "Ongoing maintenance and fault support",
      ],
      gridTitle: "Where monitoring adds value",
      gridIntro: "Monitoring is especially useful where buildings are empty overnight, cover multiple access points or rely on fast escalation when alarms trigger.",
      gridItems: [
        { title: "Out-of-hours buildings", text: "Adds awareness when a building is vacant or lightly staffed." },
        { title: "Managed estates", text: "Helps standardise response across multiple addresses or shared occupancies." },
        { title: "Higher-risk areas", text: "Useful where stock, equipment or access concerns require stronger oversight." },
      ],
      fitTitle: "Suitable for",
      fitItems: ["Commercial buildings", "Retail", "Warehouses", "Residential developments", "Managed sites"],
      ctaTitle: "Need intruder alarm monitoring that fits your response process?",
      ctaText: "We can review your current arrangement or help plan a monitored setup from the start.",
      ctaButton: "Discuss Monitoring",
    }),
    makePage({
      slug: "intruder-alarm",
      title: "Intruder Alarm",
      eyebrow: "Detection built around the site",
      intro: [
        "Intruder alarm systems help protect buildings during unoccupied periods and provide reassurance that access events or security breaches will trigger a clear response.",
        "Helix installs and maintains intruder alarm systems designed around the access patterns, risk profile and occupancy of each property.",
      ],
      image: "/security-card.png",
      imageAlt: "Intruder alarm keypad and access devices",
      metrics: [
        { value: "Detect", label: "Movement and entry events" },
        { value: "Zone", label: "Configured around the building" },
        { value: "Support", label: "Serviced over time" },
      ],
      overviewTitle: "Alarm systems configured for the way the building is used",
      overview: [
        "Every site has different entry points, usage patterns and risk areas. We set alarms up around those realities so the system is practical to arm, disarm and manage without unnecessary friction.",
      ],
      highlightsTitle: "Our intruder alarm support includes",
      highlights: [
        "System design and placement planning",
        "Keypad and detector installation",
        "Zoning aligned to the building layout",
        "Upgrades and replacement of outdated equipment",
        "Fault-finding and maintenance",
        "Support for monitored and standalone systems",
      ],
      gridTitle: "What we focus on",
      gridIntro: "The goal is not just to install an alarm, but to make sure it fits how the building is occupied and secured in real life.",
      gridItems: [
        { title: "Entry coverage", text: "Protect key doors, approach points and vulnerable access routes." },
        { title: "Internal zoning", text: "Separate areas to suit building use, occupancy and after-hours access." },
        { title: "Ease of use", text: "Help staff, residents or site teams manage the system confidently." },
      ],
      fitTitle: "Suitable for",
      fitItems: ["Offices", "Retail units", "Residential blocks", "Schools", "Warehouses", "Mixed-use sites"],
      ctaTitle: "Need a more dependable intruder alarm setup?",
      ctaText: "We can review your current system or plan a new installation around your property.",
      ctaButton: "Arrange an Alarm Review",
    }),
    makePage({
      slug: "access-control-systems",
      title: "Access Control Systems",
      eyebrow: "Manage who can enter and when",
      intro: [
        "Access control helps clients manage entry more consistently across staff doors, communal areas, restricted spaces and managed buildings.",
        "Helix installs and maintains access systems that improve day-to-day control while still keeping entry straightforward for authorised users.",
      ],
      image: "/security-card.png",
      imageAlt: "Access control and card reader equipment",
      metrics: [
        { value: "Controlled", label: "Entry management" },
        { value: "Flexible", label: "Permissions by area" },
        { value: "Visible", label: "Better oversight" },
      ],
      overviewTitle: "Access control that supports safer, smoother operations",
      overview: [
        "From staff-only areas to communal buildings and managed developments, access systems can help reduce unauthorised entry and improve day-to-day oversight.",
        "We focus on practical placement, ease of administration and systems that fit the way the building is used.",
      ],
      highlightsTitle: "Our access control service includes",
      highlights: [
        "Reader and door hardware installation",
        "Credential setup and permissions planning",
        "Entry management for shared and restricted areas",
        "Integration with wider security systems where required",
        "Repairs, upgrades and ongoing maintenance",
      ],
      gridTitle: "Access control priorities",
      gridIntro: "Most access projects centre on balancing convenience, security and visibility across who can move where.",
      gridItems: [
        { title: "Shared buildings", text: "Manage residents, visitors, contractors and staff across common entry points." },
        { title: "Restricted zones", text: "Control access to plant areas, offices, stock rooms and back-of-house spaces." },
        { title: "Admin simplicity", text: "Keep adding, removing and reviewing access straightforward for the client team." },
      ],
      fitTitle: "Suitable for",
      fitItems: ["Apartment blocks", "Commercial offices", "Schools", "Care environments", "Managed sites", "Mixed-use buildings"],
      ctaTitle: "Need tighter control over access across your property?",
      ctaText: "Talk to Helix about practical access control that works for both security and day-to-day use.",
      ctaButton: "Discuss Access Control",
    }),
  ],
};

export const resourcesCollection: SectionCollection = {
  section: "resources",
  landing: makePage({
    slug: "resources",
    title: "Resources",
    eyebrow: "Guidance, downloads and practical insight",
    intro: [
      "Our resources pages are designed to help clients better understand their responsibilities, review useful materials and access practical guidance around fire, security and compliance.",
      "Whether you are planning work, reviewing service records or looking for supporting documents, these pages give you a clearer starting point.",
    ],
    image: "/hero-helix-security.png",
    imageAlt: "Helix resource and compliance support",
    metrics: [
      { value: "Guidance", label: "Practical responsibilities" },
      { value: "Documents", label: "Useful materials" },
      { value: "Insight", label: "Support for decisions" },
    ],
    overviewTitle: "A more useful resource hub for property teams",
    overview: [
      "Resources are most valuable when they help clients act more confidently. We focus on guidance that supports real decisions around safety systems, maintenance and compliance.",
    ],
    highlightsTitle: "Use these pages to",
    highlights: [
      "Understand core responsibilities",
      "Review examples and case-study style outcomes",
      "Access document-led support",
      "Keep teams aligned around safety priorities",
      "Find answers to common operational questions",
    ],
    gridTitle: "Explore resources",
    gridIntro: "Each resource area is designed to support a different stage of the client journey, from early learning to day-to-day reference.",
    gridItems: [
      { title: "Your Responsibilities", text: "Understand the responsibilities that sit with building owners, landlords and managing teams.", href: "/resources/your-responsibilities" },
      { title: "Case Studies", text: "See examples of how integrated fire and security delivery supports real buildings.", href: "/resources/case-studies" },
      { title: "Brochures", text: "Review service overviews and supporting material in one place.", href: "/resources/brochures" },
      { title: "Downloads", text: "Find practical checklists, summaries and downloadable support documents.", href: "/resources/downloads" },
      { title: "News", text: "Stay informed on company updates, industry themes and service developments.", href: "/resources/news" },
      { title: "FAQs", text: "Answers to common questions around systems, servicing and support.", href: "/resources/faqs" },
    ],
    fitTitle: "Useful for",
    fitItems: ["Landlords", "Facilities managers", "Managing agents", "Building owners", "Operational teams"],
    ctaTitle: "Need help finding the right information for your site?",
    ctaText: "If you are unsure where to start, we can point you to the right service or next step directly.",
    ctaButton: "Ask Helix",
  }),
  pages: [
    makePage({
      slug: "your-responsibilities",
      title: "Your Responsibilities",
      eyebrow: "Know what needs to be managed",
      intro: [
        "Fire and security responsibilities sit with those managing or controlling the building. That includes making sure systems are suitable, maintained and supported with clear records.",
        "Helix helps clients turn those responsibilities into practical actions through surveys, servicing, documentation and clear communication.",
      ],
      image: "/hero-helix-security.png",
      imageAlt: "Helix responsibilities and compliance support",
      metrics: [
        { value: "Review", label: "Understand your current setup" },
        { value: "Maintain", label: "Keep systems supported" },
        { value: "Record", label: "Document actions clearly" },
      ],
      overviewTitle: "Responsibilities become easier when the service model is organised",
      overview: [
        "Most issues arise when responsibilities are split across too many disconnected providers or when records are difficult to track.",
        "A more integrated approach helps make responsibilities visible, manageable and easier to act on.",
      ],
      highlightsTitle: "Key areas usually include",
      highlights: [
        "Having suitable systems in place",
        "Maintaining equipment regularly",
        "Keeping documentation and service records current",
        "Reviewing life-safety risks in the property",
        "Ensuring escape routes and safety measures remain effective",
      ],
      gridTitle: "How Helix supports this",
      gridIntro: "We help translate responsibility into practical work plans, service schedules and documentation.",
      gridItems: [
        { title: "Surveys", text: "Review your current systems and identify priorities." },
        { title: "Maintenance", text: "Keep systems tested, serviced and operating as intended." },
        { title: "Documentation", text: "Maintain clearer records to support accountability and compliance." },
      ],
      fitTitle: "Relevant for",
      fitItems: ["Landlords", "Managing agents", "Businesses", "Facilities managers", "Property owners"],
      ctaTitle: "Need help understanding your current responsibilities?",
      ctaText: "We can review your site and help turn those obligations into a clear support plan.",
      ctaButton: "Book a Responsibilities Review",
    }),
    makePage({
      slug: "case-studies",
      title: "Case Studies",
      eyebrow: "Examples from live environments",
      intro: [
        "Case studies help show what integrated delivery looks like in practice. At Helix, that often means stronger visibility, simpler coordination and a more dependable service structure across the site.",
      ],
      image: "/hero-helix-security.png",
      imageAlt: "Operational building case study scene",
      metrics: [
        { value: "Live sites", label: "Real operating environments" },
        { value: "Integrated", label: "Joined-up delivery" },
        { value: "Practical", label: "Measured outcomes" },
      ],
      overviewTitle: "What clients usually want to understand",
      overview: [
        "Most clients want to know how a provider handled coordination, improved oversight and made ongoing service easier to manage. Those are the outcomes we focus on.",
      ],
      highlightsTitle: "Typical case-study themes",
      highlights: [
        "Replacing multiple contractors with one team",
        "Improving planned maintenance visibility",
        "Upgrading outdated fire or security systems",
        "Supporting managed residential and commercial estates",
      ],
      gridTitle: "Common outcomes",
      gridIntro: "The most valuable outcomes are often operational rather than purely technical.",
      gridItems: [
        { title: "Clearer communication", text: "One accountable team makes project and service updates easier to follow." },
        { title: "Better coordination", text: "Installation, maintenance and reporting align more cleanly." },
        { title: "Improved confidence", text: "Clients gain better visibility over what is happening across the site." },
      ],
      fitTitle: "Best for",
      fitItems: ["Decision makers reviewing providers", "Facilities teams", "Property managers", "Procurement conversations"],
      ctaTitle: "Want to talk through a similar project or service challenge?",
      ctaText: "We can outline how Helix would approach it in a structured and practical way.",
      ctaButton: "Discuss a Similar Project",
    }),
    makePage({
      slug: "brochures",
      title: "Brochures",
      eyebrow: "Service overviews in one place",
      intro: [
        "Brochures give clients a quick way to understand service areas, support models and the kinds of buildings we work with.",
        "They are helpful when comparing service scope, sharing information internally or preparing for a conversation with our team.",
      ],
      image: "/fire-systems-card.png",
      imageAlt: "Fire systems brochure-style overview",
      metrics: [
        { value: "Clear", label: "Short service summaries" },
        { value: "Useful", label: "Internal sharing" },
        { value: "Practical", label: "Starting-point documents" },
      ],
      overviewTitle: "Use brochures as a quick route into the service",
      overview: [
        "They are designed to make conversations easier by giving stakeholders a shared view of the service, the systems involved and the kind of support available.",
      ],
      highlightsTitle: "Brochure content usually covers",
      highlights: [
        "Service summaries",
        "Building types supported",
        "Maintenance and compliance focus",
        "Practical next steps for surveys and quotes",
      ],
      gridTitle: "How clients use them",
      gridIntro: "Brochures are especially useful when multiple decision makers need the same high-level picture.",
      gridItems: [
        { title: "Internal review", text: "Share a simple service summary with managers or stakeholders." },
        { title: "Procurement support", text: "Use brochure material to compare service scope and fit." },
        { title: "Early planning", text: "Get aligned on the likely next step before a survey or quote." },
      ],
      fitTitle: "Useful for",
      fitItems: ["Stakeholder reviews", "Budget planning", "Service comparisons", "Early client conversations"],
      ctaTitle: "Need a service summary tailored to your enquiry?",
      ctaText: "We can point you to the most relevant information or prepare the right next conversation.",
      ctaButton: "Request Information",
    }),
    makePage({
      slug: "downloads",
      title: "Downloads",
      eyebrow: "Useful documents and support material",
      intro: [
        "Downloads provide clients with practical materials that support planning, communication and day-to-day building management.",
        "This can include service summaries, support documents and other materials that make internal review easier.",
      ],
      image: "/fire-systems-card.png",
      imageAlt: "Downloads and documentation support",
      metrics: [
        { value: "Reference", label: "Keep materials at hand" },
        { value: "Share", label: "Distribute internally" },
        { value: "Support", label: "Make actions clearer" },
      ],
      overviewTitle: "Documentation that supports action, not clutter",
      overview: [
        "The best downloads are useful in real conversations: helping teams compare services, confirm scope and understand what needs to happen next.",
      ],
      highlightsTitle: "Examples include",
      highlights: [
        "Service summaries",
        "Support guides",
        "Operational checklists",
        "Project overviews",
        "Planning documents",
      ],
      gridTitle: "Why clients use downloads",
      gridIntro: "They help keep information consistent across teams and make planning discussions easier to manage.",
      gridItems: [
        { title: "Preparation", text: "Review information ahead of surveys, quotes or internal meetings." },
        { title: "Sharing", text: "Pass the same information to colleagues and stakeholders." },
        { title: "Reference", text: "Keep useful materials on hand for future planning or service discussions." },
      ],
      fitTitle: "Relevant for",
      fitItems: ["Facilities teams", "Property managers", "Procurement teams", "Landlords", "Operational leads"],
      ctaTitle: "Need a specific support document or service summary?",
      ctaText: "Tell us what you are reviewing and we can point you to the most useful next step.",
      ctaButton: "Request Support Material",
    }),
    makePage({
      slug: "news",
      title: "News",
      eyebrow: "Updates and industry commentary",
      intro: [
        "Our news area is intended to keep clients informed about useful service developments, company updates and broader topics affecting building safety and security support.",
      ],
      image: "/hero-helix-security.png",
      imageAlt: "Helix news and company update context",
      metrics: [
        { value: "Updates", label: "Company developments" },
        { value: "Insight", label: "Service themes" },
        { value: "Awareness", label: "Industry context" },
      ],
      overviewTitle: "Useful updates without unnecessary noise",
      overview: [
        "Clients usually care most about updates that affect service delivery, operational planning or the wider context around maintaining buildings safely and efficiently.",
      ],
      highlightsTitle: "Typical news themes",
      highlights: [
        "Company updates",
        "Service launches and improvements",
        "Industry issues affecting clients",
        "Operational guidance and commentary",
      ],
      gridTitle: "Why it matters",
      gridIntro: "Useful updates can help teams plan ahead and make better service decisions.",
      gridItems: [
        { title: "Operational awareness", text: "Understand what may affect building management or service planning." },
        { title: "Service visibility", text: "Stay informed on the way Helix continues to evolve its support model." },
        { title: "Client context", text: "Keep up with useful themes across fire, security and compliance support." },
      ],
      fitTitle: "Useful for",
      fitItems: ["Current clients", "Prospective clients", "Facilities teams", "Property managers"],
      ctaTitle: "Need help with a current issue rather than a general update?",
      ctaText: "If you have a live project or service question, we can point you to the right person quickly.",
      ctaButton: "Contact Helix",
    }),
    makePage({
      slug: "faqs",
      title: "FAQs",
      eyebrow: "Answers to common questions",
      intro: [
        "Our FAQs are designed to answer the practical questions clients often ask before booking a survey, arranging service support or reviewing a building’s current setup.",
      ],
      image: "/security-card.png",
      imageAlt: "Frequently asked questions and support context",
      metrics: [
        { value: "Simple", label: "Clear answers" },
        { value: "Practical", label: "Real client questions" },
        { value: "Useful", label: "Helps plan next steps" },
      ],
      overviewTitle: "The most common questions are usually operational",
      overview: [
        "Clients often want to know what type of system they need, how maintenance works, how quickly support can be arranged and what information to prepare before getting in touch.",
      ],
      highlightsTitle: "Frequent topics include",
      highlights: [
        "How surveys work",
        "What information helps before quoting",
        "How maintenance is scheduled",
        "How fire and security services can be combined",
        "What documentation is typically provided",
      ],
      gridTitle: "Why FAQs help",
      gridIntro: "They can make early-stage conversations more efficient and reduce uncertainty before the first call.",
      gridItems: [
        { title: "Before enquiring", text: "Get clearer on what kind of support or survey may be needed." },
        { title: "During review", text: "Use answers to align internal teams before moving ahead." },
        { title: "After installation", text: "Understand what maintenance and support typically look like." },
      ],
      fitTitle: "Useful for",
      fitItems: ["New enquiries", "Landlords", "Facilities managers", "Property teams", "Managed-site stakeholders"],
      ctaTitle: "Still have a question that is specific to your site?",
      ctaText: "Speak to our team and we will help you understand the most practical next step.",
      ctaButton: "Ask a Question",
    }),
  ],
};

export const companyCollection: SectionCollection = {
  section: "our-company",
  landing: makePage({
    slug: "our-company",
    title: "Our Company",
    eyebrow: "More than a contractor",
    intro: [
      "Helix is structured to support clients across fire systems, security solutions and compliance-focused service delivery with one accountable team.",
      "Our company pages cover the wider frameworks, standards, specialist support areas and long-term capabilities that sit behind that service model.",
    ],
    image: "/hero-helix-security.png",
    imageAlt: "Helix company overview",
    metrics: [
      { value: "Integrated", label: "Fire, security and compliance" },
      { value: "Structured", label: "Processes and frameworks" },
      { value: "Scalable", label: "Support across portfolios" },
    ],
    overviewTitle: "The wider company infrastructure behind the service",
    overview: [
      "Clients are not only buying engineering time. They are also relying on standards, systems, documentation, training and company-wide support that help service delivery stay dependable over time.",
    ],
    highlightsTitle: "These pages cover",
    highlights: [
      "Policies and standards",
      "Accreditations and memberships",
      "Framework participation",
      "Training and technical development",
      "Specialist support capabilities",
      "Wider strategic service areas",
    ],
    gridTitle: "Explore our company pages",
    gridIntro: "These areas show the infrastructure and longer-term capabilities behind the Helix service model.",
    gridItems: [
      { title: "Policies", text: "The operational and quality principles that support our service delivery.", href: "/our-company/policies" },
      { title: "Our Accreditations & Memberships", text: "Recognised bodies and standards that help underpin our work.", href: "/our-company/accreditations-memberships" },
      { title: "Frameworks", text: "How we support clients through structured procurement and service agreements.", href: "/our-company/frameworks" },
      { title: "Videos", text: "Visual content that helps explain our services and support areas.", href: "/our-company/videos" },
      { title: "Acquisitions", text: "How growth is integrated into one consistent service model.", href: "/our-company/acquisitions" },
      { title: "Alarm Receiving Centre (ARC)", text: "Monitoring-related support and the role of ARC-linked services.", href: "/our-company/alarm-receiving-centre" },
      { title: "Fire and Security Training Academy", text: "How we support technical quality through development and learning.", href: "/our-company/training-academy" },
      { title: "Consultancy", text: "Planning, review and advisory support around fire, security and compliance.", href: "/our-company/consultancy" },
    ],
    fitTitle: "Relevant for",
    fitItems: ["Procurement teams", "Portfolio owners", "Facilities managers", "Managing agents", "Public and private sector clients"],
    ctaTitle: "Need to understand the wider capability behind the service?",
    ctaText: "We can help you explore the right part of the Helix offer for your buildings and operating model.",
    ctaButton: "Talk to Helix",
  }),
  pages: [
    makePage({
      slug: "policies",
      title: "Policies",
      eyebrow: "Standards that support delivery",
      intro: [
        "Policies provide the operational foundation for quality, safety, communication and consistency across the work we deliver.",
        "For clients, that matters because good service depends on standards that are applied consistently behind the scenes as well as on site.",
      ],
      image: "/hero-helix-security.png",
      imageAlt: "Policy and standards support",
      metrics: [
        { value: "Quality", label: "Consistent standards" },
        { value: "Safety", label: "Operational discipline" },
        { value: "Clarity", label: "Documented processes" },
      ],
      overviewTitle: "Policies that support day-to-day reliability",
      overview: [
        "Strong policies shape how work is planned, delivered, reviewed and communicated. They help create a service model clients can rely on over time.",
      ],
      highlightsTitle: "Common policy areas include",
      highlights: [
        "Quality management",
        "Health and safety practices",
        "Operational consistency",
        "Documentation and reporting discipline",
        "Continuous improvement and review",
      ],
      gridTitle: "Why this matters to clients",
      gridIntro: "Policies help create predictable standards, especially across larger estates and long-term service arrangements.",
      gridItems: [
        { title: "Consistency", text: "Helps reduce variation in how work is planned and delivered." },
        { title: "Accountability", text: "Supports clearer expectations, records and service reviews." },
        { title: "Confidence", text: "Clients benefit from more dependable behind-the-scenes structure." },
      ],
      fitTitle: "Useful for",
      fitItems: ["Procurement review", "Due diligence", "Portfolio clients", "Compliance-led organisations"],
      ctaTitle: "Need to understand how Helix supports consistent delivery?",
      ctaText: "We can talk you through the processes and standards behind our work.",
      ctaButton: "Request Company Information",
    }),
    makePage({
      slug: "accreditations-memberships",
      title: "Our Accreditations & Memberships",
      eyebrow: "Recognised standards and industry alignment",
      intro: [
        "Accreditations and memberships help demonstrate that service delivery is supported by recognised standards, assessment and industry engagement.",
        "They are one part of the wider quality picture that clients often review when choosing a long-term fire and security partner.",
      ],
      image: "/hero-helix-security.png",
      imageAlt: "Accreditation and membership overview",
      metrics: [
        { value: "Recognised", label: "Industry standards" },
        { value: "Assessed", label: "External review" },
        { value: "Trusted", label: "Better client confidence" },
      ],
      overviewTitle: "Why accreditations matter",
      overview: [
        "They help support confidence in the way systems are installed, maintained and documented, particularly where consistency and accountability matter over the long term.",
      ],
      highlightsTitle: "What clients often look for",
      highlights: [
        "Evidence of recognised standards",
        "Independent assessment",
        "Alignment with industry expectations",
        "Confidence during procurement and review",
      ],
      gridTitle: "How this supports better service",
      gridIntro: "Formal standards are most useful when they strengthen real delivery, not just marketing messages.",
      gridItems: [
        { title: "Quality confidence", text: "Supports trust in process, workmanship and documentation." },
        { title: "Procurement support", text: "Useful when clients are comparing providers or completing due diligence." },
        { title: "Long-term reassurance", text: "Helps show the company is working within recognised frameworks and expectations." },
      ],
      fitTitle: "Useful for",
      fitItems: ["Procurement teams", "Managing agents", "Facilities managers", "Public sector buyers", "Corporate stakeholders"],
      ctaTitle: "Need more detail on accreditations or service standards?",
      ctaText: "Our team can help explain what is relevant to your buildings and tender requirements.",
      ctaButton: "Discuss Accreditations",
    }),
    makePage({
      slug: "frameworks",
      title: "Frameworks",
      eyebrow: "Structured procurement and support models",
      intro: [
        "Framework participation can help clients access services through more structured procurement routes and clearly defined service arrangements.",
        "Helix supports clients who need a provider capable of working within formal frameworks, agreed scopes and longer-term delivery models.",
      ],
      image: "/hero-helix-security.png",
      imageAlt: "Framework-based service delivery",
      metrics: [
        { value: "Structured", label: "Procurement-friendly" },
        { value: "Scalable", label: "Portfolio support" },
        { value: "Clear", label: "Defined scope and process" },
      ],
      overviewTitle: "Why frameworks matter",
      overview: [
        "For many organisations, frameworks make procurement clearer and service delivery easier to standardise across multiple properties or ongoing programmes of work.",
      ],
      highlightsTitle: "Benefits often include",
      highlights: [
        "Clearer routes to appointing service partners",
        "Better alignment across multi-site work",
        "Defined scope, standards and expectations",
        "Support for longer-term planning",
      ],
      gridTitle: "Where they are useful",
      gridIntro: "Frameworks are especially valuable for organisations with recurring service needs or multiple buildings to manage.",
      gridItems: [
        { title: "Portfolio clients", text: "Support standardised service across estates or multiple addresses." },
        { title: "Planned programmes", text: "Useful where work needs to be delivered in structured phases." },
        { title: "Long-term support", text: "Helps align service planning, reporting and delivery over time." },
      ],
      fitTitle: "Relevant for",
      fitItems: ["Public sector", "Housing", "Corporate estates", "Managing agents", "Large property portfolios"],
      ctaTitle: "Need a service partner able to support structured procurement?",
      ctaText: "We can discuss how Helix fits into framework-led or portfolio-based delivery models.",
      ctaButton: "Discuss Framework Support",
    }),
    makePage({
      slug: "videos",
      title: "Videos",
      eyebrow: "Visual service explainers",
      intro: [
        "Video content can help explain systems, services and responsibilities more clearly than text alone, especially when multiple stakeholders need the same overview.",
        "Helix uses visual material to make service understanding faster and easier.",
      ],
      image: "/hero-helix-security.png",
      imageAlt: "Helix video and media content",
      metrics: [
        { value: "Visual", label: "Clearer explanations" },
        { value: "Shareable", label: "Internal alignment" },
        { value: "Simple", label: "Faster understanding" },
      ],
      overviewTitle: "Why video can be useful",
      overview: [
        "For clients reviewing responsibilities, service scope or building support options, visual material can speed up internal understanding and decision-making.",
      ],
      highlightsTitle: "Typical video themes",
      highlights: [
        "Service explainers",
        "Responsibility summaries",
        "Client education content",
        "Operational support themes",
      ],
      gridTitle: "How clients use them",
      gridIntro: "Visual content is particularly useful when explaining services to wider internal teams.",
      gridItems: [
        { title: "Internal sharing", text: "Help stakeholders quickly understand a service area or support need." },
        { title: "Education", text: "Use visual material to explain responsibilities and system functions." },
        { title: "Faster onboarding", text: "Bring new contacts up to speed on site support more quickly." },
      ],
      fitTitle: "Useful for",
      fitItems: ["Clients with multiple stakeholders", "Property managers", "Facilities teams", "Resident-facing environments"],
      ctaTitle: "Need help understanding a service area visually?",
      ctaText: "We can guide you to the most useful material or talk it through directly.",
      ctaButton: "Request More Information",
    }),
    makePage({
      slug: "acquisitions",
      title: "Acquisitions",
      eyebrow: "Growth integrated carefully",
      intro: [
        "When service businesses grow, clients want confidence that standards, communication and accountability will stay consistent.",
        "Helix approaches growth with a focus on integrating people, systems and delivery expectations into one dependable model.",
      ],
      image: "/hero-helix-security.png",
      imageAlt: "Company growth and integration",
      metrics: [
        { value: "Integrated", label: "One delivery model" },
        { value: "Stable", label: "Consistent standards" },
        { value: "Aligned", label: "Shared service expectations" },
      ],
      overviewTitle: "Why integration matters",
      overview: [
        "For clients, acquisitions only matter if the result is stronger capability without creating inconsistency or confusion in delivery.",
      ],
      highlightsTitle: "Our focus is on",
      highlights: [
        "Maintaining clear standards",
        "Aligning systems and processes",
        "Protecting client communication",
        "Strengthening capability without fragmenting service",
      ],
      gridTitle: "Client-facing priorities",
      gridIntro: "Growth should feel like stronger support, not more complexity.",
      gridItems: [
        { title: "Continuity", text: "Keep service standards and communication stable during change." },
        { title: "Capability", text: "Use growth to expand expertise and wider support capacity." },
        { title: "Consistency", text: "Deliver one clearer operating model rather than disconnected parts." },
      ],
      fitTitle: "Relevant for",
      fitItems: ["Long-term clients", "Portfolio owners", "Procurement teams", "Managing agents"],
      ctaTitle: "Want to understand the capability behind Helix’s wider growth model?",
      ctaText: "We can explain how the business is structured to keep service quality aligned.",
      ctaButton: "Talk to Us",
    }),
    makePage({
      slug: "alarm-receiving-centre",
      title: "Alarm Receiving Centre (ARC)",
      eyebrow: "Monitoring-linked support",
      intro: [
        "Alarm Receiving Centre support is relevant where clients need monitored alarm events handled through a structured escalation path rather than relying on local awareness alone.",
        "Helix helps clients understand how ARC-linked support fits into the wider fire and security service model.",
      ],
      image: "/security-card.png",
      imageAlt: "Alarm receiving and monitoring context",
      metrics: [
        { value: "Monitored", label: "Escalated awareness" },
        { value: "Structured", label: "Defined response path" },
        { value: "Supported", label: "Integrated maintenance" },
      ],
      overviewTitle: "Monitoring is part of a wider operational setup",
      overview: [
        "ARC services are most effective when alarm configuration, communication paths, maintenance and client expectations are all aligned.",
      ],
      highlightsTitle: "Key considerations include",
      highlights: [
        "Suitable alarm and communication setup",
        "Defined response expectations",
        "Reliable maintenance and testing",
        "Clear understanding of escalation routes",
      ],
      gridTitle: "How Helix supports this",
      gridIntro: "We help ensure the monitored setup fits the site and wider support model.",
      gridItems: [
        { title: "System readiness", text: "Support configuration and maintenance that help monitoring work effectively." },
        { title: "Client understanding", text: "Clarify how ARC-linked services operate and what clients should expect." },
        { title: "Long-term support", text: "Keep the wider alarm system maintained and dependable over time." },
      ],
      fitTitle: "Suitable for",
      fitItems: ["Monitored commercial sites", "Residential developments", "Managed estates", "Higher-risk buildings"],
      ctaTitle: "Need guidance on monitored alarm support or ARC-linked services?",
      ctaText: "We can review your current setup and help explain the most practical way forward.",
      ctaButton: "Discuss Monitoring Support",
    }),
    makePage({
      slug: "training-academy",
      title: "Fire and Security Training Academy",
      eyebrow: "Investing in technical quality",
      intro: [
        "Strong service depends on strong people. Training and ongoing development are part of how Helix supports technical quality across fire and security delivery.",
      ],
      image: "/security-card.png",
      imageAlt: "Training and development environment",
      metrics: [
        { value: "Learning", label: "Continuous development" },
        { value: "Standards", label: "Technical consistency" },
        { value: "Growth", label: "Long-term capability" },
      ],
      overviewTitle: "Why training matters to clients too",
      overview: [
        "Training is not just an internal benefit. It supports better installation quality, more dependable maintenance and stronger confidence in the people delivering the work.",
      ],
      highlightsTitle: "A strong training culture helps deliver",
      highlights: [
        "Better technical consistency",
        "Stronger fault-finding and support",
        "Improved confidence across teams",
        "Long-term investment in delivery quality",
      ],
      gridTitle: "What this supports",
      gridIntro: "Ongoing development strengthens both day-to-day service and longer-term business capability.",
      gridItems: [
        { title: "Engineers", text: "Support technical growth and confidence across real project environments." },
        { title: "Client outcomes", text: "Better-trained teams usually deliver more dependable work." },
        { title: "Long-term standards", text: "Development helps keep capability strong as the business grows." },
      ],
      fitTitle: "Relevant for",
      fitItems: ["Clients reviewing capability", "Long-term support contracts", "Procurement review", "Quality-led service relationships"],
      ctaTitle: "Want to understand the capability behind the people delivering your service?",
      ctaText: "We can explain how training and development support stronger delivery standards.",
      ctaButton: "Request More Information",
    }),
    makePage({
      slug: "consultancy",
      title: "Consultancy",
      eyebrow: "Planning and advisory support",
      intro: [
        "Some clients need more than installation or maintenance. They need help reviewing a current setup, shaping the right scope or planning a more structured path forward across fire, security and compliance.",
        "Helix provides consultancy-led support to help make those decisions clearer.",
      ],
      image: "/hero-helix-security.png",
      imageAlt: "Consultancy and planning support",
      metrics: [
        { value: "Review", label: "Assess the current position" },
        { value: "Plan", label: "Shape the next step" },
        { value: "Clarify", label: "Reduce uncertainty" },
      ],
      overviewTitle: "Consultancy that helps teams make practical decisions",
      overview: [
        "This is useful where sites have inherited issues, fragmented service arrangements or uncertainty around the best route forward.",
      ],
      highlightsTitle: "Consultancy support can include",
      highlights: [
        "Reviewing current system arrangements",
        "Helping define service priorities",
        "Advising on integrated delivery options",
        "Supporting project planning conversations",
      ],
      gridTitle: "Where it adds value",
      gridIntro: "Consultancy is most helpful when clients need clarity before committing to wider works or support arrangements.",
      gridItems: [
        { title: "Early-stage planning", text: "Understand options before moving to installation or maintenance changes." },
        { title: "Portfolio review", text: "Compare needs across multiple buildings and plan a more consistent support model." },
        { title: "Problem solving", text: "Untangle complex or fragmented service arrangements with clearer recommendations." },
      ],
      fitTitle: "Suitable for",
      fitItems: ["Managing agents", "Portfolio owners", "Facilities teams", "Complex estates", "Clients reviewing current providers"],
      ctaTitle: "Need help reviewing your current setup before moving ahead?",
      ctaText: "We can provide a more strategic conversation around what your buildings need next.",
      ctaButton: "Book a Consultancy Call",
    }),
  ],
};

export const standalonePages = {
  customerPortal: makePage({
    slug: "customer-portal",
    title: "Customer Portal",
    eyebrow: "Visibility across service activity",
    intro: [
      "A customer portal helps make service information easier to access, review and manage across active buildings and support arrangements.",
      "Helix uses portal-led visibility to support clearer oversight across reporting, records and operational follow-up.",
    ],
    image: "/hero-helix-security.png",
    imageAlt: "Digital customer portal overview",
    metrics: [
      { value: "Visible", label: "Records and updates" },
      { value: "Central", label: "One location for information" },
      { value: "Practical", label: "Supports day-to-day review" },
    ],
    overviewTitle: "Better access to the information clients actually need",
    overview: [
      "Portals are most useful when they make service actions, documents and updates easier to follow rather than harder to find.",
    ],
    highlightsTitle: "A portal can help support",
    highlights: [
      "Service visibility",
      "Document access",
      "Review of completed actions",
      "Better communication across teams",
    ],
    gridTitle: "What clients value most",
    gridIntro: "The best portal experience reduces friction and helps client teams stay aligned.",
    gridItems: [
      { title: "Access", text: "Get to the information you need without chasing multiple contacts." },
      { title: "Clarity", text: "Review service activity and records in one place." },
      { title: "Consistency", text: "Support portfolio-wide visibility and more organised follow-up." },
    ],
    fitTitle: "Useful for",
    fitItems: ["Facilities teams", "Managing agents", "Portfolio owners", "Operational stakeholders"],
    ctaTitle: "Want to understand how Helix supports clearer visibility across service activity?",
    ctaText: "We can walk you through the type of information and support structure available.",
    ctaButton: "Ask About the Portal",
  }),
  terms: makePage({
    slug: "terms",
    title: "Terms & Conditions",
    eyebrow: "Clear expectations and service understanding",
    intro: [
      "Terms and conditions help define how services are provided, how work is scoped and what both parties can expect through the relationship.",
      "If you need a document-specific legal review, our team can direct you to the right contact.",
    ],
    image: "/hero-helix-security.png",
    imageAlt: "Terms and conditions overview",
    metrics: [
      { value: "Clear", label: "Service expectations" },
      { value: "Practical", label: "Relationship structure" },
      { value: "Defined", label: "Working arrangements" },
    ],
    overviewTitle: "Why terms matter",
    overview: [
      "They help create clarity around scope, responsibility and the practical framework that supports service delivery.",
    ],
    highlightsTitle: "Common areas covered",
    highlights: ["Scope of services", "Service arrangements", "Commercial understanding", "Responsibilities and expectations"],
    gridTitle: "Need help?",
    gridIntro: "If you need clarification on a live service arrangement, we can help direct your enquiry appropriately.",
    gridItems: [
      { title: "General questions", text: "Speak to us if you need help understanding how support is structured." },
      { title: "Live arrangements", text: "We can direct current clients to the right team for contract-related questions." },
    ],
    fitTitle: "Relevant for",
    fitItems: ["Current clients", "Procurement teams", "Contract reviewers"],
    ctaTitle: "Need help with a live contract or service arrangement?",
    ctaText: "Contact our team and we will point you to the right next conversation.",
    ctaButton: "Contact Us",
  }),
  privacy: makePage({
    slug: "privacy",
    title: "Privacy Policy",
    eyebrow: "How information is handled",
    intro: [
      "Privacy information explains how client and enquiry details are handled as part of the Helix service relationship.",
      "For any detailed privacy-related question, our team can help direct your enquiry appropriately.",
    ],
    image: "/hero-helix-security.png",
    imageAlt: "Privacy and data handling overview",
    metrics: [
      { value: "Respectful", label: "Information handling" },
      { value: "Clear", label: "Data understanding" },
      { value: "Supported", label: "Client queries" },
    ],
    overviewTitle: "Why privacy matters",
    overview: [
      "Clients want confidence that enquiries, project information and service records are handled appropriately as part of the wider support model.",
    ],
    highlightsTitle: "Topics often include",
    highlights: ["Client contact details", "Service-related information", "Enquiry handling", "Operational communications"],
    gridTitle: "Need more detail?",
    gridIntro: "If you have a specific privacy-related question, we can point you to the right route.",
    gridItems: [
      { title: "General enquiries", text: "Ask us if you need help understanding how your information is handled." },
      { title: "Specific concerns", text: "We can direct privacy-related questions through the appropriate channel." },
    ],
    fitTitle: "Relevant for",
    fitItems: ["Website enquiries", "Clients", "Prospective clients"],
    ctaTitle: "Need help with a privacy-related question?",
    ctaText: "Let us know what you need and we will direct your enquiry appropriately.",
    ctaButton: "Contact Helix",
  }),
};

export const collections = {
  about: aboutCollection,
  security: securityCollection,
  resources: resourcesCollection,
  "our-company": companyCollection,
} as const;

export function getSectionLanding(section: keyof typeof collections) {
  return collections[section].landing;
}

export function getSectionPage(section: keyof typeof collections, slug: string) {
  return collections[section].pages.find((page) => page.slug === slug);
}
